/* =============================================================
   CHARACTER OF THE CHAPTER — 字 zì
   One key Chinese character per chapter, in brushstroke type,
   with its components broken open and a memorable image so the
   reader leaves the chapter holding a piece of the language.
   - char          : the character itself
   - py            : tone-marked pinyin
   - meaning       : 1–3 short English meanings
   - breakdown     : etymology — what it's built from
   - mnemonic      : a memorable image that ties the parts together
   - chapter_pivot : how this character anchors the chapter's argument
   - strokes       : total stroke count (used to size the widget)
   - stroke_guide  : [{n, move, note}] — step-by-step for simple chars (≤7)
                     Displayed alongside the hanzi-writer animation.
   ============================================================ */
window.CHARACTERS = {
  1:  { char:"道", py:"dào",   meaning:"the Way · path · to speak",
        breakdown:"辶 chuò (walking) + 首 shǒu (head)",
        breakdown_th:"辶 chuò (การเดิน) + 首 shǒu (ศีรษะ)",
        mnemonic:"A head 首 walking 辶 down a road. The path you walk is your way. The path the universe walks is THE Way.",
        mnemonic_th:"ศีรษะ 首 ที่กำลังเดิน 辶 ไปตามทาง ทางที่คุณเดินคือ 'ทาง' ของคุณ ทางที่จักรวาลเดินคือ 'ทาง' ตัวจริง",
        chapter_pivot:"道 also means 'to speak.' Chapter 1's pun: the way that can be spoken (道) is not the constant way (道). Same character, two reads — and the second read undoes the first.",
        chapter_pivot_th:"道 ยังแปลว่า 'พูด' ด้วย บทแรกจึงมีการเล่นคำ: ทาง (道) ที่พูดได้ (道) ไม่ใช่ทางแท้ ตัวอักษรเดียวกัน สองความหมาย และความหมายที่สองทำลายความหมายแรก" },
  2:  { char:"美", py:"měi",   meaning:"beautiful · lovely",
        breakdown:"羊 yáng (sheep) + 大 dà (big)",
        mnemonic:"A big 大 sheep 羊. In ancient agrarian China, a fat sheep was beauty itself — wealth, dinner, and ornament rolled into one. The character smells faintly of mutton.",
        chapter_pivot:"Chapter 2: the moment 美 is named, its opposite arrives. Even the etymology contains the herder's eye." },
  3:  { char:"賢", py:"xián",  meaning:"worthy · wise · capable",
        breakdown:"臣 chén (minister) + 又 yòu (hand) + 貝 bèi (shell, money)",
        mnemonic:"A minister's 臣 hand 又 holds the money 貝. 'Worthy' originally meant 'good with the assets.'",
        chapter_pivot:"Chapter 3: stop publicly rewarding 賢 and people stop fighting for the title. The signal is the disease." },
  4:  { char:"沖", py:"chōng", meaning:"empty · pour · surge",
        breakdown:"氵 shuǐ (water) + 中 zhōng (middle)",
        mnemonic:"Water 氵 in the middle 中 — the still center of a vessel that pours forever.",
        chapter_pivot:"Chapter 4: 道沖 — the way is 沖 (empty), yet using it never fills. Capacity is the absence of pre-existing pattern." },
  5:  { char:"仁", py:"rén",   meaning:"benevolence · humaneness",
        breakdown:"亻 rén (person) + 二 èr (two)",
        mnemonic:"Two 二 people 亻. Benevolence is what happens between two — never alone.",
        chapter_pivot:"Chapter 5: heaven is NOT 仁. It has nothing to do with the relational two. Heaven is impersonal — and that is the harder mercy." },
  6:  { char:"谷", py:"gǔ",    meaning:"valley · gorge",
        breakdown:"two slopes opening into 口 kǒu (mouth, opening)",
        mnemonic:"A mouth 口 with two slopes opening into it. The character itself is a valley seen head-on.",
        chapter_pivot:"Chapter 6: 谷神不死 — 'the valley spirit does not die.' The receptive shape is the durable shape." },
  7:  { char:"私", py:"sī",    meaning:"private · selfish",
        breakdown:"禾 hé (grain) + 厶 sī (an old curve, originally meaning 'private')",
        mnemonic:"Grain 禾 you've curled 厶 around for yourself. The character holds back its own harvest.",
        chapter_pivot:"Chapter 7: heaven is enduring because it has 無私 — no grain held back for itself." },
  8:  { char:"水", py:"shuǐ",  meaning:"water",
        breakdown:"a single pictograph — flowing center stroke with two side drops",
        breakdown_th:"ภาพวาดตัวอักษรภาษาจีนโบราณ — เส้นกลางที่ไหลลง พร้อมหยดน้ำสองข้าง",
        mnemonic:"Look at the character: it's literally water — a stream with droplets to either side.",
        mnemonic_th:"ดูที่ตัวอักษร — มันคือน้ำจริง ๆ สายน้ำที่มีหยดน้ำสองฝั่ง",
        chapter_pivot:"Chapter 8: 上善若水 — 'the highest good is like water.' Water doesn't push back, so it never stores the impact that breaks rocks.",
        chapter_pivot_th:"บทที่ 8: 上善若水 — 'ความดีสูงสุดเหมือนน้ำ' น้ำไม่ดันกลับ จึงไม่สะสมแรงกระแทกที่จะทำให้ตัวเองแตก",
        strokes: 4,
        stroke_guide:[
          {n:1, move:"Center: one stroke downward with a small hook left at the bottom.", note:"The spine of the river."},
          {n:2, move:"Left of center: short diagonal stroke curving downward-left.", note:"Left bank of the river."},
          {n:3, move:"Left: short upward flick, starting low.", note:"A splash."},
          {n:4, move:"Right of center: long diagonal stroke curving downward-right.", note:"Right bank — water finding its way."}
        ] },
  9:  { char:"盈", py:"yíng",  meaning:"full · brimming · overflow",
        breakdown:"乃 nǎi + 又 yòu + 皿 mǐn (vessel)",
        mnemonic:"A vessel 皿 brimming. The character itself looks heavy.",
        chapter_pivot:"Chapter 9: 持而盈之，不如其已 — holding while brim-full, better stop now. Knowing when to stop is the only skill that scales." },
  10: { char:"嬰", py:"yīng",  meaning:"infant · baby",
        breakdown:"賏 (twin cowrie shells, ornaments) + 女 nǚ (woman)",
        mnemonic:"A woman 女 with twin little ornaments 賏 — the new baby and its tiny adornments.",
        chapter_pivot:"Chapter 10: 專氣致柔，能嬰兒乎 — 'concentrate qi until soft as 嬰?' Softness is not weakness; it's the opposite of stiffness." },
  11: { char:"無", py:"wú",    meaning:"non-being · nothing · without",
        breakdown:"originally a pictograph of a dancer with feathered streamers — full of motion, no fixed thing",
        breakdown_th:"ต้นกำเนิดจากภาพนักเต้นรำที่มีขนนกสะบัดไหว — เต็มไปด้วยการเคลื่อนไหว ไม่มีสิ่งใดตายตัว",
        mnemonic:"Picture a dancer with flowing sleeves. There's no thing there — only motion, only emptiness moving.",
        mnemonic_th:"จินตนาการนักเต้นที่แขนเสื้อสะบัดตาม ไม่มีสิ่งใดอยู่ตรงนั้น — มีแต่การเคลื่อนไหว มีแต่ความว่างที่เคลื่อน",
        chapter_pivot:"Chapter 11: 無之以為用 — 'non-being is what makes the room a room.' The void IS the deliverable.",
        chapter_pivot_th:"บทที่ 11: 無之以為用 — 'ความว่างคือสิ่งที่ทำให้ห้องเป็นห้อง' ช่องว่างคือสิ่งที่ส่งมอบได้จริง" },
  12: { char:"腹", py:"fù",    meaning:"belly · stomach",
        breakdown:"月 yuè (flesh, here for body) + 复 fù (return)",
        mnemonic:"The flesh 月 of the body that returns 复 to need food again. The seat of basic, recurring desire.",
        chapter_pivot:"Chapter 12: 為腹不為目 — 'for the 腹 (belly), not for the 目 (eye).' Feed the basic; don't feed the manufactured." },
  13: { char:"寵", py:"chǒng", meaning:"favor · pet · be doted on",
        breakdown:"宀 mián (roof) + 龍 lóng (dragon)",
        mnemonic:"A dragon 龍 (the king) under your roof 宀. The dragon keeps you close — that's favor.",
        chapter_pivot:"Chapter 13: 寵辱若驚 — 'favor and disgrace startle equally.' Same neural circuit, opposite directions." },
  14: { char:"微", py:"wēi",   meaning:"subtle · tiny · faint",
        breakdown:"彳 chì (small step) + 散 (a faint, scattering motion)",
        mnemonic:"A small step 彳 you almost don't notice. The character whispers itself.",
        chapter_pivot:"Chapter 14: look, you don't see; listen, you don't hear; grasp, you don't catch — 微 names the not-quite-there." },
  15: { char:"涉", py:"shè",   meaning:"wade · ford · cross water",
        breakdown:"氵 shuǐ (water) + 步 bù (step)",
        mnemonic:"Stepping 步 through water 氵. The body of the character is doing the wading.",
        chapter_pivot:"Chapter 15: the old masters move 'as if 涉 a frozen river' — careful, unrushed, alert at every step." },
  16: { char:"靜", py:"jìng",  meaning:"stillness · quiet",
        breakdown:"青 qīng (clear, blue-green) + 爭 zhēng (struggle, contest)",
        mnemonic:"Clear 青 + struggle 爭. True stillness is the clear settling AFTER the noise stops, not the absence of noise.",
        chapter_pivot:"Chapter 16: 歸根曰靜 — 'returning to the root is called 靜.' Stillness is the brain's housekeeping cycle." },
  17: { char:"信", py:"xìn",   meaning:"trust · sincerity · letter",
        breakdown:"亻 rén (person) + 言 yán (speech)",
        mnemonic:"A person 亻 + their words 言. If the words match the person, you have 信.",
        chapter_pivot:"Chapter 17: 信不足焉，有不信焉 — 'when the leader's 信 falls short, the people stop trusting.' Best leader: barely seen. Worst: words don't match person." },
  18: { char:"廢", py:"fèi",   meaning:"abandon · ruin · disuse",
        breakdown:"广 yǎn (shelter) + 發 fā (release, discharge)",
        mnemonic:"Releasing 發 from under shelter 广 — letting it go to ruin.",
        chapter_pivot:"Chapter 18: 大道廢，有仁義 — 'when the great way is 廢, then benevolence appears.' Once a virtue has to be named, it is already in trouble." },
  19: { char:"樸", py:"pǔ",    meaning:"uncarved block · plain · simple",
        breakdown:"木 mù (wood, tree) + 業 yè (work, grain pattern)",
        mnemonic:"Raw wood 木 with the original grain 業 still showing — wood not yet shaped into a chair.",
        chapter_pivot:"Chapter 19: 見素抱樸 — 'see the plain, hold the 樸.' Less culture, not more." },
  20: { char:"母", py:"mǔ",    meaning:"mother",
        breakdown:"a pictograph of a kneeling woman with two dots for nursing breasts",
        mnemonic:"A figure with two dots — the mother's nursing breasts. The character is anatomy turned into ink.",
        chapter_pivot:"Chapter 20: 我獨異於人，而貴食母 — 'I alone differ, and value being fed by the 母.' The introvert's quiet food source.",
        strokes: 5,
        stroke_guide:[
          {n:1, move:"Short diagonal left, then fold right — the head bowing.", note:"Think of a mother bending toward her child."},
          {n:2, move:"Left side: vertical stroke down, then fold right at the base.", note:"The left wall of the body."},
          {n:3, move:"Right side: stroke down and across.", note:"The right wall closes the body."},
          {n:4, move:"Small dot upper-left inside.", note:"One breast — the first gift."},
          {n:5, move:"Small dot upper-right inside.", note:"The other breast — the source."}
        ] },
  21: { char:"德", py:"dé",    meaning:"virtue · charisma · power",
        breakdown:"彳 chì (walk) + 直 zhí (straight) + 心 xīn (heart)",
        breakdown_th:"彳 chì (เดิน) + 直 zhí (ตรง) + 心 xīn (หัวใจ)",
        mnemonic:"A heart 心 walking 彳 straight 直. 德 is virtue you can walk in — not virtue you talk about.",
        mnemonic_th:"หัวใจ 心 ที่เดิน 彳 ตรง 直 ไป 德 คือคุณธรรมที่เดินได้จริง ไม่ใช่คุณธรรมที่พูดเฉย ๆ",
        chapter_pivot:"Chapter 21: 孔德之容，惟道是從 — 'the substance of 德 follows only the way.' Slingerland: charisma you cannot fake.",
        chapter_pivot_th:"บทที่ 21: เนื้อแท้ของ 德 ตามทางเท่านั้น Slingerland เรียกมันว่า 'เสน่ห์ที่ปลอมไม่ได้'" },
  22: { char:"曲", py:"qū",    meaning:"bend · crooked · tune",
        breakdown:"a pictograph of a bent ruler or a bent fish-trap",
        mnemonic:"A character that itself bends. Look at it: it isn't straight.",
        chapter_pivot:"Chapter 22: 曲則全 — 'bend, then whole.' Bending is how you survive what would break the straight." },
  23: { char:"風", py:"fēng",  meaning:"wind",
        breakdown:"凡 fán (mast, sail) + 虫 chóng (creature, here a sky-creature)",
        mnemonic:"A creature 虫 under a mast 凡 — the sailor's wind, the unseen force that fills sails.",
        chapter_pivot:"Chapter 23: 飄風不終朝 — 'a strong 風 doesn't last a morning.' Nothing forced sustains itself." },
  24: { char:"企", py:"qǐ",    meaning:"tiptoe · yearn · plan",
        breakdown:"人 rén (person) over 止 zhǐ (foot)",
        mnemonic:"A person 人 standing on toes 止 — the foot raised, the body unstable.",
        chapter_pivot:"Chapter 24: 企者不立 — 'the one on tiptoes does not stand.' Stretch only makes you fall faster." },
  25: { char:"自", py:"zì",    meaning:"self · from · oneself",
        breakdown:"originally a pictograph of a nose — Chinese still point at their nose to mean 'me'",
        mnemonic:"A nose drawn in profile. In ancient Chinese, 'self' was 'this nose right here.'",
        chapter_pivot:"Chapter 25: 道法自然 — 'the way models on 自然' (zì rán = 'self-so'). The Way follows what is so OF ITSELF.",
        strokes: 6,
        stroke_guide:[
          {n:1, move:"Short vertical stroke at top center — the bridge of the nose.", note:""},
          {n:2, move:"Horizontal across the top.", note:"The brow ridge."},
          {n:3, move:"Left vertical down.", note:"Left side of the nose."},
          {n:4, move:"Short horizontal middle-left.", note:"A nostril."},
          {n:5, move:"Short horizontal middle-right.", note:"The other nostril."},
          {n:6, move:"Horizontal across the base.", note:"The foundation — self resting on itself."}
        ] },
  26: { char:"重", py:"zhòng", meaning:"heavy · weight · important",
        breakdown:"千 qiān (thousand) + 里 lǐ (mile)",
        mnemonic:"A load that takes a thousand 千 miles 里 to carry. Heavy.",
        chapter_pivot:"Chapter 26: 重為輕根 — 'heaviness is the root of lightness.' The calm center is where movement actually lives." },
  27: { char:"跡", py:"jì",    meaning:"trace · footprint · track",
        breakdown:"足 zú (foot) + 亦 yì (also)",
        mnemonic:"A foot 足 leaves a trace too 亦. The mark you didn't mean to make.",
        chapter_pivot:"Chapter 27: 善行無轍跡 — 'good walking leaves no 跡.' The doer's signature is missing on purpose." },
  28: { char:"雌", py:"cí",    meaning:"female (animal)",
        breakdown:"此 cǐ (this) + 隹 zhuī (short-tailed bird)",
        mnemonic:"This 此 short-tailed bird 隹 — the hen, not the rooster.",
        chapter_pivot:"Chapter 28: 知雄守雌 — 'know the male, keep the 雌.' Know the strong; live in the soft." },
  29: { char:"神", py:"shén",  meaning:"sacred · spirit · divine",
        breakdown:"礻 shì (altar) + 申 shēn (lightning, declare)",
        mnemonic:"Lightning 申 over an altar 礻 — the moment of revelation.",
        chapter_pivot:"Chapter 29: 天下神器，不可為也 — 'the world is a sacred 器 (vessel); you cannot grip it.' The harder you grip, the more it spoils." },
  30: { char:"兵", py:"bīng",  meaning:"soldier · weapon · troops",
        breakdown:"斤 jīn (axe) + 廾 gǒng (two hands)",
        mnemonic:"Two hands 廾 wielding an axe 斤. The character is the weapon.",
        chapter_pivot:"Chapter 30: where 兵 has been, thorns grow. Force has a way of returning to the one who used it." },
  31: { char:"器", py:"qì",    meaning:"tool · vessel · instrument",
        breakdown:"four 口 kǒu (mouths) around 犬 quǎn (dog)",
        mnemonic:"Four mouths 口 barking around a dog 犬. A 'tool' was originally something many mouths spoke about.",
        chapter_pivot:"Chapter 31: 兵者不祥之器 — 'weapons are tools of mourning.' When you must use them, use them like a funeral." },
  32: { char:"名", py:"míng",  meaning:"name",
        breakdown:"夕 xī (evening) + 口 kǒu (mouth)",
        mnemonic:"An evening 夕 mouth 口 — calling your name in the dark, when the face has disappeared.",
        chapter_pivot:"Chapter 32: 道常無名 — 'the way has no constant 名.' Every name shrinks the thing." },
  33: { char:"知", py:"zhī",   meaning:"know · be aware · wisdom",
        breakdown:"矢 shǐ (arrow) + 口 kǒu (mouth)",
        mnemonic:"Arrow 矢 + mouth 口 — speech as fast and accurate as an arrow. To know is to be able to say truly.",
        chapter_pivot:"Chapter 33: 自知者明 — 'one who 知 the self is clear.' Knowing yourself is calibration, not modesty." },
  34: { char:"大", py:"dà",    meaning:"great · big",
        breakdown:"a person 人 with arms outstretched as wide as they go",
        mnemonic:"Look at the character: it IS a person opening their arms wide.",
        chapter_pivot:"Chapter 34: 大道氾兮 — 'the 大 way overflows everywhere.' What is truly great does not announce itself.",
        strokes: 3,
        stroke_guide:[
          {n:1, move:"Horizontal across the middle — the arms opened wide.", note:"One stroke, left to right, unhurried."},
          {n:2, move:"Diagonal downward-left — the left leg.", note:""},
          {n:3, move:"Diagonal downward-right — the right leg.", note:"Person standing, arms open. Three strokes for a whole human body."}
        ] },
  35: { char:"象", py:"xiàng", meaning:"image · sign · elephant",
        breakdown:"a pictograph of an elephant — trunk, body, legs, tail",
        mnemonic:"Look sideways: that's an elephant. Chinese has used the elephant as the metaphor for 'great image' since antiquity.",
        chapter_pivot:"Chapter 35: 執大象 — 'hold the great 象.' Hold the pattern, and the world comes to you." },
  36: { char:"弱", py:"ruò",   meaning:"weak · soft · pliable",
        breakdown:"two 弓 gōng (bows) with feathered ornaments — soft, unstrung bows",
        mnemonic:"Two unstrung bows — beautiful, not yet drawn, still pliable.",
        chapter_pivot:"Chapter 36: 柔弱勝剛強 — '柔 (soft) and 弱 (weak) overcome hard and strong.' The law of reversal." },
  37: { char:"為", py:"wéi",   meaning:"to do · to act · for the sake of",
        breakdown:"originally a hand grasping an elephant — to make, to handle",
        mnemonic:"A hand on an elephant — the act of guiding something larger than yourself. To do is to move.",
        chapter_pivot:"Chapter 37: 道常無為而無不為 — 'the way is constantly 無為 (not-doing), and yet nothing is left undone.'" },
  38: { char:"上", py:"shàng", meaning:"above · upper · top",
        breakdown:"a horizontal line above another — the simplest ideogram of 'above'",
        mnemonic:"Mark above a line. Higher than the baseline. That's all 上 ever was.",
        chapter_pivot:"Chapter 38: 上德不德，是以有德 — 'the 上 (highest) virtue is not virtuous, therefore it is virtue.' The substance leaves the moment the signal arrives.",
        strokes: 3,
        stroke_guide:[
          {n:1, move:"Short horizontal at the top.", note:"The raised mark — what is above."},
          {n:2, move:"Short vertical downward in the center.", note:"Connecting above to below."},
          {n:3, move:"Long horizontal at the base.", note:"The ground line. 上 is simply: a mark above a line. The entire concept of 'above' in three strokes."}
        ] },
  39: { char:"一", py:"yī",    meaning:"one · single · whole",
        breakdown:"a single horizontal stroke",
        mnemonic:"One stroke = one. Drawn once and the lesson is over.",
        chapter_pivot:"Chapter 39: 昔之得一者 — 'those of old who attained the One.' The unifying thread under everything.",
        strokes: 1,
        stroke_guide:[
          {n:1, move:"One horizontal stroke, left to right, held steady.", note:"The only character in Chinese that is exactly what it means — one line, one thing. The Dao De Jing spends 81 chapters trying to describe something that 一 gets in a single stroke."}
        ] },
  40: { char:"反", py:"fǎn",   meaning:"return · reverse · oppose",
        breakdown:"厂 hǎn (cliff) + 又 yòu (hand)",
        mnemonic:"A hand 又 reaching back from a cliff 厂 — to reverse, to come back.",
        chapter_pivot:"Chapter 40: 反者道之動 — '反 is the way's motion.' The way moves by going back, not forward.",
        strokes: 4,
        stroke_guide:[
          {n:1, move:"Short diagonal line top-left — the cliff edge 厂.", note:"The precipice."},
          {n:2, move:"Longer diagonal down-left from the cliff top.", note:"The cliff face."},
          {n:3, move:"Short horizontal right, lower center.", note:"The hand 又 reaching out."},
          {n:4, move:"Sweeping stroke downward with a leftward hook.", note:"The hand reversing direction — pulling back. This is the whole character's meaning in a single motion."}
        ] },
  41: { char:"笑", py:"xiào",  meaning:"laugh",
        breakdown:"竹 zhú (bamboo) over 夭 yāo (bend)",
        mnemonic:"Bamboo 竹 bending 夭 — the supple swaying of laughter, body shaken.",
        chapter_pivot:"Chapter 41: 下士聞道，大笑之 — 'the lowest student hears the way and 大笑 (laughs out loud).' Their laughter is the only honest part of their reaction." },
  42: { char:"萬", py:"wàn",   meaning:"ten thousand · myriad",
        breakdown:"a pictograph of a scorpion — used because '10,000' was beyond counting",
        mnemonic:"Ten thousand scorpions — too many to count, exactly the point.",
        chapter_pivot:"Chapter 42: 三生萬物 — 'three produces the 萬 things.' Three is the threshold of complexity." },
  43: { char:"柔", py:"róu",   meaning:"soft · supple · pliable",
        breakdown:"矛 máo (spear-shaft) + 木 mù (wood)",
        mnemonic:"A spear-shaft 矛 of wood 木 — strong, but supple. Bends, doesn't break.",
        chapter_pivot:"Chapter 43: 天下之至柔，馳騁天下之至堅 — 'the 柔 rides through the hardest.' Softness wins by phase." },
  44: { char:"足", py:"zú",    meaning:"enough · foot · sufficient",
        breakdown:"a pictograph of a foot — 口 (rounded shape) + 止 (stop)",
        mnemonic:"A foot that has stopped — and is therefore enough.",
        chapter_pivot:"Chapter 44: 知足不辱 — 'know what is 足, no disgrace.' The contentment of contentment is the only contentment that doesn't run out." },
  45: { char:"缺", py:"quē",   meaning:"incomplete · missing · flaw",
        breakdown:"缶 fǒu (jar) + 夬 guài (broken)",
        mnemonic:"A jar 缶 with a broken 夬 piece — incomplete, but still useable.",
        chapter_pivot:"Chapter 45: 大成若缺 — 'great completion looks 缺.' The final polish is the one not applied." },
  46: { char:"慾", py:"yù",    meaning:"desire · craving · lust",
        breakdown:"谷 gǔ (valley) + 欠 qiàn (yawn) + 心 xīn (heart)",
        mnemonic:"A heart 心 yawning 欠 toward an empty valley 谷 — endless want.",
        chapter_pivot:"Chapter 46: 罪莫大於可慾 — 'no crime greater than indulged 慾.' The opposite is 知足 — knowing enough." },
  47: { char:"戶", py:"hù",    meaning:"door · household",
        breakdown:"a pictograph of a single-leaf door (vs 門 mén, the double door)",
        mnemonic:"One door-leaf. Hinge on the right, opening to the left.",
        chapter_pivot:"Chapter 47: 不出戶，知天下 — 'without leaving the 戶, know the world.' Knowing happens inside, not on the road." },
  48: { char:"損", py:"sǔn",   meaning:"diminish · subtract · loss",
        breakdown:"扌 shǒu (hand) + 員 yuán (count)",
        mnemonic:"A hand 扌 reducing the count 員. Subtraction itself.",
        chapter_pivot:"Chapter 48: 為道日損 — 'in the way, daily 損 (decrease).' The Marie Kondo of philosophy, 2,500 years early." },
  49: { char:"善", py:"shàn",  meaning:"good · kind · skilled",
        breakdown:"羊 yáng (sheep) over 言 yán (speech)",
        mnemonic:"Speech 言 about a sheep 羊 — the soft, agreeable register. Good is what a herd-tending voice sounds like.",
        chapter_pivot:"Chapter 49: 善者吾善之，不善者吾亦善之 — 'the 善 I treat as 善; the not-善 I also treat as 善.' Universal kindness is a posture, not a calculation." },
  50: { char:"死", py:"sǐ",    meaning:"death",
        breakdown:"歹 dǎi (bone fragment) + 匕 bǐ (kneeling person)",
        mnemonic:"A person 匕 beside bone fragments 歹 — what was once living, now not.",
        chapter_pivot:"Chapter 50: 出生入死 — 'come out into life, go in toward 死.' The trick is not to keep stepping over the door on purpose." },
  51: { char:"育", py:"yù",    meaning:"nurture · raise · educate",
        breakdown:"子 zǐ (child) inverted + 月 yuè (flesh)",
        mnemonic:"A small child being raised — flesh of the parent, body of the child.",
        chapter_pivot:"Chapter 51: 道生之，德畜之 — 'the way births it; 德 (virtue) 育 (nurtures) it.' You neither own nor steer." },
  52: { char:"子", py:"zǐ",    meaning:"child · son · master (suffix)",
        breakdown:"a pictograph of an infant in swaddling, arms wrapped",
        mnemonic:"An infant with arms swaddled, head visible. Tiny, dependent, full of potential.",
        chapter_pivot:"Chapter 52: 既得其母，以知其子 — 'find the 母 (mother), then know the 子 (child).' Roots first, leaves second.",
        strokes: 3,
        stroke_guide:[
          {n:1, move:"Curved stroke from upper-right sweeping down-left, then up and right — the whole infant body swaddled.", note:"One continuous curved stroke like a baby wrapped in a blanket."},
          {n:2, move:"Short horizontal crossing through the upper middle — the wrapped arms.", note:"Arms held close, bundled."},
          {n:3, move:"Short horizontal at the bottom center.", note:"The feet — barely visible, peeking out of the blanket."}
        ] },
  53: { char:"盜", py:"dào",   meaning:"thief · banditry · steal",
        breakdown:"次 cì (next, eyeing) + 皿 mǐn (vessel)",
        mnemonic:"Eyeing 次 someone else's vessel 皿 — the bandit's want.",
        chapter_pivot:"Chapter 53: 服文采，帶利劍...是謂盜誇 — 'fancy clothes and sharp swords... this is called proud 盜.' A society that flaunts wealth is a society of bandits in costume." },
  54: { char:"修", py:"xiū",   meaning:"cultivate · repair · refine",
        breakdown:"攸 yōu (long flowing water) + 彡 shān (brushstrokes)",
        mnemonic:"Long flowing water 攸 with patient brushstrokes 彡 — slow cultivation, repeated.",
        chapter_pivot:"Chapter 54: 修之於身，其德乃真 — '修 (cultivate) in the body, virtue becomes real.' Practice in the small before applying in the large." },
  55: { char:"赤", py:"chì",   meaning:"red · bare · infant",
        breakdown:"大 dà (big) over 火 huǒ (fire)",
        mnemonic:"Big 大 fire 火 — the red of the new. Also 'bare,' the bare of an infant's skin.",
        chapter_pivot:"Chapter 55: 含德之厚，比於赤子 — 'thickness of virtue is like a 赤 (newborn).' Soft, unguarded, somehow harder to harm." },
  56: { char:"言", py:"yán",   meaning:"speech · word",
        breakdown:"二 èr (two horizontal breaths) over 口 kǒu (mouth)",
        mnemonic:"A mouth 口 with breath-lines 二 coming out. Speech itself, drawn.",
        chapter_pivot:"Chapter 56: 知者不言，言者不知 — 'the knower does not 言, the 言-er does not know.' Hot listening looks like silence." },
  57: { char:"奇", py:"qí",    meaning:"strange · extraordinary · odd",
        breakdown:"大 dà (big) + 可 kě (can, permit)",
        mnemonic:"Bigger 大 than what is permitted 可 — extraordinary.",
        chapter_pivot:"Chapter 57: 以正治國，以奇用兵 — 'govern with the straight, fight with the 奇.' The unexpected is the soldier's only edge." },
  58: { char:"福", py:"fú",    meaning:"fortune · blessing",
        breakdown:"礻 shì (altar) + 畐 fú (full vessel)",
        mnemonic:"A full vessel 畐 on an altar 礻 — the harvest blessing.",
        chapter_pivot:"Chapter 58: 禍兮福之所倚 — '禍 (misfortune) is what 福 leans on.' Comfort is where trouble is already growing." },
  59: { char:"嗇", py:"sè",    meaning:"frugal · sparing · stingy",
        breakdown:"來 lái (wheat) + 回 huí (storehouse)",
        mnemonic:"Wheat 來 in the storehouse 回 — saved, not eaten.",
        chapter_pivot:"Chapter 59: 治人事天，莫若嗇 — 'in governing people, nothing beats 嗇.' Restraint is the unsexy superpower." },
  60: { char:"烹", py:"pēng",  meaning:"cook · boil",
        breakdown:"亨 hēng (offer, heat) + 灬 huǒ (fire)",
        mnemonic:"Heat 亨 from fire 灬 — cooking, slowly, all four corners.",
        chapter_pivot:"Chapter 60: 治大國，若烹小鮮 — 'govern a great state like 烹 a small fish.' Disturb it less than you think you should." },
  61: { char:"下", py:"xià",   meaning:"below · down · low",
        breakdown:"a horizontal line with a mark below it",
        mnemonic:"Mark below the line. Mirror image of 上 (above).",
        chapter_pivot:"Chapter 61: 大邦者下流 — 'a great country sits 下 (downstream).' Greatness is gravity, not advertising.",
        strokes: 3,
        stroke_guide:[
          {n:1, move:"Long horizontal across the top — the line of reference.", note:"The baseline from which 'below' is measured."},
          {n:2, move:"Short vertical downward in the center.", note:"Descending below the line."},
          {n:3, move:"Small dot below and to the right.", note:"The mark that says: here, beneath. Compare to 上 — same three strokes, opposite arrangement."}
        ] },
  62: { char:"奧", py:"ào",    meaning:"depth · secret · interior",
        breakdown:"宀 mián (roof) + 大 dà (big) + 釆 (separate)",
        mnemonic:"A big 大 inner separation 釆 under a roof 宀 — the deep room of the house, not the front entry.",
        chapter_pivot:"Chapter 62: 道者，萬物之奧 — 'the way is the 奧 of the 萬 things.' The hidden compartment everything keeps." },
  63: { char:"易", py:"yì",    meaning:"easy · change · exchange",
        breakdown:"日 rì (sun) + 勿 wù (banner, do-not)",
        mnemonic:"Sun 日 above a banner 勿 — light shifting easily across cloth.",
        chapter_pivot:"Chapter 63: 圖難於其易 — 'plan the hard while it is 易.' Tackle the hard while it's still easy; tackle the great while it's still small." },
  64: { char:"安", py:"ān",    meaning:"peace · safe · settled",
        breakdown:"宀 mián (roof) + 女 nǚ (woman)",
        mnemonic:"A woman 女 under a roof 宀 — the old picture of household peace. The etymology is what it is.",
        chapter_pivot:"Chapter 64: 其安易持 — 'what is 安 is easy to hold.' Intervene before, not during.",
        strokes: 6,
        stroke_guide:[
          {n:1, move:"Dot upper-left — the left slope of the roof 宀.", note:""},
          {n:2, move:"Sweep down-left then right across the top — the full roof ridge.", note:"The shelter."},
          {n:3, move:"Short diagonal left — the first stroke of 女 (woman), like an arm out.", note:""},
          {n:4, move:"Diagonal stroke sweeping right, crossing the arm.", note:"The body."},
          {n:5, move:"Short horizontal left.", note:""},
          {n:6, move:"Longer horizontal right at the base of 女.", note:"Feet planted. Woman under roof. Peace."}
        ] },
  65: { char:"愚", py:"yú",    meaning:"foolish · simple",
        breakdown:"禺 yú (monkey) + 心 xīn (heart)",
        mnemonic:"A monkey 禺 heart 心 — simple, unthinking. The Daoist 愚 is unselfconscious, not stupid.",
        chapter_pivot:"Chapter 65: 將以愚之 — 'use 愚 to keep the people whole.' Sophistication breeds the wrong cleverness." },
  66: { char:"江", py:"jiāng", meaning:"large river · the Yangtze",
        breakdown:"氵 shuǐ (water) + 工 gōng (work)",
        mnemonic:"Water 氵 doing work 工 — the great industrial river.",
        chapter_pivot:"Chapter 66: 江海所以能為百谷王者，以其善下之 — 'the 江-and-sea is king of a hundred valleys because it stays 下 (below) them.'" },
  67: { char:"慈", py:"cí",    meaning:"compassion · loving-kindness",
        breakdown:"茲 zī (this, abundant) + 心 xīn (heart)",
        mnemonic:"An abundant 茲 heart 心 — compassion as a heart with more than enough to give.",
        chapter_pivot:"Chapter 67: 我有三寶，一曰慈 — 'I have three treasures; the first is 慈.' Drop one and the other two collapse." },
  68: { char:"武", py:"wǔ",    meaning:"martial · military",
        breakdown:"止 zhǐ (stop) + 戈 gē (halberd)",
        mnemonic:"A halberd 戈 stopping 止. The original 武 meant 'to stop war.' True martial skill ENDS conflict.",
        chapter_pivot:"Chapter 68: 善為士者不武 — 'the good warrior is not 武.' The best fighter does not show fight." },
  69: { char:"客", py:"kè",    meaning:"guest · visitor",
        breakdown:"宀 mián (roof) + 各 gè (each, every)",
        mnemonic:"Each 各 person under your roof 宀 — a guest. The house is yours; the seat is theirs.",
        chapter_pivot:"Chapter 69: 吾不敢為主而為客 — 'I dare not be host; I would rather be 客.' In conflict, prefer the position with nothing to lose." },
  70: { char:"貴", py:"guì",   meaning:"precious · valuable · noble",
        breakdown:"中 (basket) over 貝 bèi (cowrie shell, money)",
        mnemonic:"Money 貝 carefully held in a basket — what is precious.",
        chapter_pivot:"Chapter 70: 知我者希，則我者貴 — 'those who know me are rare; those who follow me are 貴.' My words are easy and almost no one understands them." },
  71: { char:"病", py:"bìng",  meaning:"illness · defect · ailment",
        breakdown:"疒 (sickness frame) + 丙 bǐng (internal heat)",
        mnemonic:"A bed 疒 with internal heat 丙 — illness.",
        chapter_pivot:"Chapter 71: 不知知，病 — 'not knowing, yet thinking you know — that is the 病.' Knowing-that-you-don't-know is the highest knowing." },
  72: { char:"威", py:"wēi",   meaning:"awe · majesty · threat",
        breakdown:"戌 xū (halberd) + 女 nǚ (woman)",
        mnemonic:"An armed figure 戌 over a woman 女 — the original picture of intimidation. The character carries the bruise.",
        chapter_pivot:"Chapter 72: 民不畏威，則大威至 — 'when the people stop fearing 威, the real 威 has arrived.' That is not their 威." },
  73: { char:"網", py:"wǎng",  meaning:"net · web",
        breakdown:"糹 sī (silk) + 罔 wǎng (net frame)",
        mnemonic:"Silk 糹 woven into a net 罔. Soft material, firm shape.",
        chapter_pivot:"Chapter 73: 天網恢恢，疏而不失 — 'heaven's 網 is wide and loose-meshed, yet nothing slips through.'" },
  74: { char:"司", py:"sī",    meaning:"to manage · official · take charge",
        breakdown:"𠂉 (banner) over 口 kǒu (mouth)",
        mnemonic:"A banner over a mouth 口 — the one who issues commands.",
        chapter_pivot:"Chapter 74: 司殺者 — 'the 司 of killing.' Don't take the executioner's job; the executioner is heaven, not you." },
  75: { char:"飢", py:"jī",    meaning:"hungry · famine",
        breakdown:"食 shí (food) + 几 jī (small table)",
        mnemonic:"Food 食 by a small table 几 — wanting it, waiting for it.",
        chapter_pivot:"Chapter 75: 民之飢，以其上食稅之多 — 'the people are 飢 because their rulers eat too much in taxes.'" },
  76: { char:"強", py:"qiáng", meaning:"strong · stiff · forced",
        breakdown:"弓 gōng (bow) + 厶 + 虫 chóng (insect)",
        mnemonic:"A bow 弓 drawn so tight even an insect 虫 strains it — over-tight strength.",
        chapter_pivot:"Chapter 76: 堅強者死之徒，柔弱者生之徒 — '堅強 belongs to death, 柔弱 belongs to life.'" },
  77: { char:"弓", py:"gōng",  meaning:"bow (the weapon) · to curve",
        breakdown:"a pictograph of a bow with the string loose",
        mnemonic:"The shape itself — a curved bow.",
        chapter_pivot:"Chapter 77: 天之道，其猶張弓與 — 'the way of heaven is like drawing a 弓.' Lower the high, raise the low — heaven redistributes.",
        strokes: 3,
        stroke_guide:[
          {n:1, move:"Curved stroke down-right then folding left with a hook — the bow's body.", note:"Hold the brush as you would hold a bow. One connected motion, tension built into the curve."},
          {n:2, move:"Short horizontal left at middle — like the arrow notch.", note:""},
          {n:3, move:"Short horizontal left at the base — the grip.", note:"Three strokes. A weapon, a tool, a metaphor. The chapter uses it as the simplest diagram of redistribution: the top is pulled down; the bottom is lifted up."}
        ] },
  78: { char:"攻", py:"gōng",  meaning:"attack · assault",
        breakdown:"工 gōng (work) + 攵 pū (strike)",
        mnemonic:"Work 工 with a strike 攵 — focused attack.",
        chapter_pivot:"Chapter 78: 攻堅強者莫之能勝 — 'in 攻 (attacking) the hard, nothing surpasses water.' Soft overcomes hard, and everyone in the world knows this and almost no one practices it." },
  79: { char:"怨", py:"yuàn",  meaning:"resentment · grievance",
        breakdown:"夗 yuàn (twist, grievance) + 心 xīn (heart)",
        mnemonic:"A twisted 夗 heart 心 — old grievance, knotted.",
        chapter_pivot:"Chapter 79: 報怨以德 — 'repay 怨 with 德.' Settled grievances always leave a residue; the wise person holds the unfavorable half." },
  80: { char:"寡", py:"guǎ",   meaning:"few · scarce · widowed",
        breakdown:"宀 mián (roof) + 頁 yè (head) + 八 bā (split)",
        mnemonic:"Under a roof 宀, one head 頁 split off 八 — alone, few.",
        chapter_pivot:"Chapter 80: 小國寡民 — 'small country, 寡 people.' Tools enough but used little; food sweet, customs joyful." },
  81: { char:"利", py:"lì",    meaning:"benefit · sharp · advantage",
        breakdown:"禾 hé (grain) + 刂 dāo (knife)",
        mnemonic:"A blade 刂 cutting grain 禾 — the harvest, the benefit. The same character also means 'sharp.' Tools cut both ways.",
        chapter_pivot:"Chapter 81: 天之道，利而不害 — 'the way of heaven 利 (benefits) without harming.' The book closes with the knife that gives, not the knife that takes." }
};
