/* =============================================================
   CLOSING QUESTIONS — 問 wèn
   At the end of every chapter, one question that almost anyone
   has felt. Trilingual. Direct. Recognisable. The "have you ever"
   moment that makes the chapter land in the body, not just the head.
   ============================================================ */
window.CLOSERS = {
  1:  { en:"Have you ever tried to explain something you love, only to feel every word make it smaller?",
        th:"เคยไหม ที่พยายามอธิบายสิ่งที่คุณรักให้ใครฟัง แล้วพบว่าทุกคำที่หลุดออกไปทำให้มันเล็กลง?" },
  2:  { en:"Have you ever called something beautiful, and immediately noticed what was ugly right next to it?",
        th:"เคยไหม ที่เพิ่งเรียกอะไรว่าสวย แล้วทันใดนั้นก็เห็นความน่าเกลียดที่อยู่ข้าง ๆ?" },
  3:  { en:"Have you ever caught yourself wanting something only because someone else was holding it up?",
        th:"เคยไหม ที่จับได้ว่าตัวเองอยากได้บางอย่าง เพียงเพราะมีคนชูมันขึ้นมาให้ดู?" },
  4:  { en:"Have you ever found a quiet room more useful, somehow, than a full one?",
        th:"เคยไหม ที่รู้สึกว่าห้องที่ว่างเปล่ากลับมีประโยชน์ มากกว่าห้องที่อัดแน่นไปด้วยของ?" },
  5:  { en:"Have you ever felt better the moment you stopped taking it personally?",
        th:"เคยไหม ที่รู้สึกดีขึ้นทันที ในวินาทีที่หยุดคิดว่าเรื่องนี้เกิดขึ้นเพื่อจะทำร้ายคุณ?" },
  6:  { en:"Have you ever been the listener in the room — and noticed you were the one who got remembered?",
        th:"เคยไหม ที่เป็นคนฟังในห้องนั้น แล้วพบว่าตัวเองคือคนที่คนอื่นจำได้?" },
  7:  { en:"Have you ever lost track of yourself doing work that mattered, and felt strangely whole afterwards?",
        th:"เคยไหม ที่ทำงานสำคัญจนลืมตัวเอง แล้วเสร็จออกมาแล้วกลับรู้สึกเป็นตัวเองมากกว่าเดิม?" },
  8:  { en:"Have you ever pushed back against someone you love — and noticed you were the only one bruised?",
        th:"เคยไหม ที่ดันสู้กับคนที่คุณรัก แล้วสุดท้ายคนที่ฟกช้ำคือตัวคุณคนเดียว?" },
  9:  { en:"Have you ever tried so hard to reach something and missed it, then later got it just by sitting still?",
        th:"เคยไหม ที่พยายามเท่าไรก็ไปไม่ถึง แต่บางครั้ง อยู่เฉย ๆ ก็ได้สิ่งที่อยากได้มาเอง?" },
  10: { en:"Have you ever held your breath in a hard moment, then felt the moment pass the second you let it go?",
        th:"เคยไหม ที่กลั้นหายใจในจังหวะยาก ๆ แล้ววินาทีที่ปล่อยลม ทุกอย่างก็คลี่คลายเอง?" },
  11: { en:"Have you ever loved a room not for its furniture, but for the empty space between the furniture?",
        th:"เคยไหม ที่รักห้องห้องหนึ่ง ไม่ใช่เพราะเฟอร์นิเจอร์ แต่เพราะที่ว่างระหว่างเฟอร์นิเจอร์?" },
  12: { en:"Have you ever bought something that looked perfect online, and felt nothing the moment it arrived?",
        th:"เคยไหม ที่ซื้อของที่ดูเพอร์เฟกต์ในออนไลน์ แล้วตอนของมาถึงบ้าน กลับไม่รู้สึกอะไรเลย?" },
  13: { en:"Have you ever felt nervous waiting for praise — and just as nervous waiting for blame?",
        th:"เคยไหม ที่ใจสั่นรอคำชม แล้วก็ใจสั่นเหมือนกันรอคำตำหนิ?" },
  14: { en:"Have you ever sensed something important in the room without quite being able to point at it?",
        th:"เคยไหม ที่รู้สึกว่ามีอะไรสำคัญอยู่ในห้อง โดยไม่สามารถชี้ออกมาได้เลยว่ามันคืออะไร?" },
  15: { en:"Have you ever watched someone move through a hard moment so quietly you barely noticed it was hard?",
        th:"เคยไหม ที่เห็นใครสักคนผ่านช่วงที่ยากลำบากอย่างเงียบ ๆ จนคุณเกือบไม่รู้ตัวว่ามันยาก?" },
  16: { en:"Have you ever come back from a long walk with the answer you'd been chasing at your desk?",
        th:"เคยไหม ที่กลับจากการเดินยาว ๆ พร้อมคำตอบที่นั่งหาที่โต๊ะทำงานเป็นชั่วโมงไม่เจอ?" },
  17: { en:"Have you ever worked under a leader you barely noticed — and only realized they were good after they left?",
        th:"เคยไหม ที่ทำงานกับผู้นำที่คุณแทบไม่สังเกต แล้วเพิ่งรู้ว่าเขาเก่ง ตอนเขาไปแล้ว?" },
  18: { en:"Have you ever noticed that the words 'integrity' and 'transparency' got loud the moment they got rare?",
        th:"เคยไหม ที่สังเกตว่าคำว่า \"คุณธรรม\" และ \"ความโปร่งใส\" ดังขึ้นพอดี ในยุคที่มันหายาก?" },
  19: { en:"Have you ever felt better in a country with fewer rules, even though you couldn't say why?",
        th:"เคยไหม ที่รู้สึกดีขึ้นในที่ที่กฎน้อยลง แม้คุณบอกไม่ได้ว่าเพราะอะไร?" },
  20: { en:"Have you ever felt out of step with everyone at the party, and quietly known you were not wrong?",
        th:"เคยไหม ที่รู้สึกไม่เข้าจังหวะกับใครเลยในงานเลี้ยง และในใจก็รู้ว่าตัวคุณไม่ได้ผิด?" },
  21: { en:"Have you ever met someone whose virtue you couldn't quite name, only feel?",
        th:"เคยไหม ที่เจอใครสักคน ซึ่งคุณรู้สึกได้ถึงคุณธรรมของเขา โดยที่บอกไม่ออกว่ามันคือคุณธรรมข้อไหน?" },
  22: { en:"Have you ever bent — and noticed the storm broke around you instead of breaking you?",
        th:"เคยไหม ที่ยอมโค้งให้สถานการณ์ แล้วพบว่าพายุพัดผ่านไปโดยไม่หักคุณ?" },
  23: { en:"Have you ever tried to force a conversation, and watched it die in your hands?",
        th:"เคยไหม ที่พยายามฝืนให้บทสนทนาเดินต่อ แล้วดูมันตายในมือคุณเอง?" },
  24: { en:"Have you ever stood on tiptoes for someone, and felt your knees give out?",
        th:"เคยไหม ที่เขย่งปลายเท้าให้ใคร แล้วเข่าตัวเองอ่อนทรุดลง?" },
  25: { en:"Have you ever felt that something was right not because someone said so, but because it just was?",
        th:"เคยไหม ที่รู้สึกว่าบางอย่างถูก ไม่ใช่เพราะใครบอก แต่เพราะมันถูกของมันเอง?" },
  26: { en:"Have you ever felt safer with someone who was calm than with someone who was correct?",
        th:"เคยไหม ที่รู้สึกปลอดภัยกับคนที่นิ่ง มากกว่ากับคนที่ถูกต้อง?" },
  27: { en:"Have you ever been helped by someone who left so little trace, you forgot to thank them?",
        th:"เคยไหม ที่มีคนช่วยคุณโดยทิ้งร่องรอยไว้น้อยมาก จนคุณลืมขอบคุณเขา?" },
  28: { en:"Have you ever lost an argument by winning it?",
        th:"เคยไหม ที่แพ้ศึกใดศึกหนึ่งโดยการชนะมัน?" },
  29: { en:"Have you ever tried to grip something tighter, and felt it slip away faster?",
        th:"เคยไหม ที่ยิ่งกำสิ่งใดให้แน่นขึ้น มันยิ่งหลุดมือคุณเร็วขึ้น?" },
  30: { en:"Have you ever taken a swing at a problem and watched the bruise come back to you?",
        th:"เคยไหม ที่เหวี่ยงหมัดใส่ปัญหา แล้วรอยช้ำกลับมาที่ตัวคุณเอง?" },
  31: { en:"Have you ever 'won' a fight and felt strangely heavier afterwards?",
        th:"เคยไหม ที่ \"ชนะ\" การทะเลาะแล้วรู้สึกหนักอกมากกว่าเดิม?" },
  32: { en:"Have you ever met someone whose silence said more than anyone else's argument?",
        th:"เคยไหม ที่เจอคนซึ่งความเงียบของเขาบอกอะไรได้มากกว่า การถกเถียงของใครทั้งหมด?" },
  33: { en:"Have you ever known a thousand things about other people, and almost nothing about yourself?",
        th:"เคยไหม ที่รู้เรื่องคนอื่นเป็นพัน แต่แทบไม่รู้อะไรเกี่ยวกับตัวเองเลย?" },
  34: { en:"Have you ever helped someone in a way they never noticed, and felt that was the cleanest help you ever gave?",
        th:"เคยไหม ที่ช่วยใครโดยที่เขาไม่รู้ตัว แล้วรู้สึกว่ามันคือการช่วยที่สะอาดที่สุดที่เคยทำ?" },
  35: { en:"Have you ever held a steady tune in a noisy room, and watched everyone slowly come to listen?",
        th:"เคยไหม ที่ฮัมเพลงเงียบ ๆ ในห้องที่อึกทึก แล้วเห็นทุกคนค่อย ๆ หันมาฟัง?" },
  36: { en:"Have you ever let something rise so it could fall on its own?",
        th:"เคยไหม ที่ปล่อยให้บางอย่างขึ้นไปสุด เพื่อให้มันร่วงลงเองตามแรงโน้มถ่วงของมัน?" },
  37: { en:"Have you ever stopped meddling and watched the thing you were managing run perfectly fine without you?",
        th:"เคยไหม ที่หยุดยุ่งกับมัน แล้วเห็นสิ่งที่คุณจัดการอยู่เดินไปได้ดีโดยไม่มีคุณ?" },
  38: { en:"Have you ever felt ESG reports louder than the goodness they were supposed to track?",
        th:"เคยไหม ที่รู้สึกว่ารายงานความยั่งยืนเสียงดังกว่าความดีที่มันบอกว่ากำลังวัดอยู่?" },
  39: { en:"Have you ever felt held together by one thread you couldn't quite name?",
        th:"เคยไหม ที่รู้สึกว่าตัวเองถูกยึดไว้ด้วยเส้นด้ายเส้นเดียวที่คุณบอกชื่อไม่ออก?" },
  40: { en:"Have you ever come back to a place you left, and recognised it as forward progress?",
        th:"เคยไหม ที่กลับไปยังที่ที่จากมา แล้วรับรู้ว่ามันคือการก้าวไปข้างหน้า?" },
  41: { en:"Have you ever laughed at advice that, ten years later, turned out to be exactly right?",
        th:"เคยไหม ที่หัวเราะคำแนะนำของใคร แล้วสิบปีต่อมารู้ว่ามันถูกที่สุด?" },
  42: { en:"Have you ever felt that your shadow was as much a part of you as your face?",
        th:"เคยไหม ที่รู้สึกว่าเงาของคุณเป็นส่วนหนึ่งของคุณ พอ ๆ กับใบหน้า?" },
  43: { en:"Have you ever watched water find a way through stone over time, and recognised yourself in it?",
        th:"เคยไหม ที่เห็นน้ำหาทางผ่านหินไปได้เมื่อเวลาผ่าน แล้วเห็นตัวเองในนั้น?" },
  44: { en:"Have you ever finally had everything you said you wanted, and felt nothing in particular?",
        th:"เคยไหม ที่ในที่สุดก็มีทุกอย่างที่เคยบอกว่าอยากได้ แล้วกลับไม่รู้สึกอะไรเป็นพิเศษ?" },
  45: { en:"Have you ever loved a piece of art precisely because of where the artist stopped working?",
        th:"เคยไหม ที่หลงรักงานศิลปะ เพราะตรงที่ศิลปินตัดสินใจหยุดมือ?" },
  46: { en:"Have you ever felt the thing you were chasing go quieter the moment you stopped chasing it?",
        th:"เคยไหม ที่สิ่งที่คุณไล่ตามเงียบลง ในวินาทีที่คุณหยุดไล่ตามมัน?" },
  47: { en:"Have you ever known what was going on in a room without leaving your chair?",
        th:"เคยไหม ที่รู้ว่ามีอะไรกำลังเกิดขึ้นในห้องนั้น โดยไม่ลุกจากเก้าอี้?" },
  48: { en:"Have you ever done less, on purpose, and gotten more done?",
        th:"เคยไหม ที่ตั้งใจทำน้อยลง แล้วงานเสร็จมากขึ้น?" },
  49: { en:"Have you ever met someone who treated everyone like a friend, and noticed strangers became their friends?",
        th:"เคยไหม ที่เจอคนซึ่งปฏิบัติต่อทุกคนราวกับเพื่อน แล้วเห็นคนแปลกหน้ากลายเป็นเพื่อนของเขา?" },
  50: { en:"Have you ever felt how thin the wall between life and death is, in a perfectly ordinary moment?",
        th:"เคยไหม ที่รู้สึกว่ากำแพงระหว่างความเป็นกับความตายบางมาก ในวินาทีธรรมดา ๆ?" },
  51: { en:"Have you ever raised someone or something well by getting out of its way?",
        th:"เคยไหม ที่เลี้ยงดูใครหรืออะไรได้ดี โดยการถอยออกห่างจากมัน?" },
  52: { en:"Have you ever traced a problem back to its mother, and watched the children solve themselves?",
        th:"เคยไหม ที่สาวปัญหากลับไปหารากของมัน แล้วเห็นปลายทางคลี่คลายเอง?" },
  53: { en:"Have you ever passed a beautifully dressed person and felt, instinctively, that something was off?",
        th:"เคยไหม ที่เดินผ่านคนแต่งตัวสวยมาก แล้วสัญชาตญาณบอกคุณว่ามีบางอย่างไม่ใช่?" },
  54: { en:"Have you ever fixed something tiny in yourself, and noticed your whole household ease?",
        th:"เคยไหม ที่แก้สิ่งเล็ก ๆ ในตัวเอง แล้วทั้งบ้านพลอยผ่อนคลายตาม?" },
  55: { en:"Have you ever envied a child's softness — and known it was strength, not weakness?",
        th:"เคยไหม ที่อิจฉาความอ่อนของเด็กเล็ก และรู้ว่ามันคือความแข็งแรง ไม่ใช่ความอ่อนแอ?" },
  56: { en:"Have you ever stopped composing your reply mid-sentence, and noticed the conversation become real?",
        th:"เคยไหม ที่หยุดเรียบเรียงคำตอบกลางประโยค แล้วบทสนทนาเริ่มเป็นของจริง?" },
  57: { en:"Have you ever solved something by doing the unexpected thing, only to be told afterwards it was obvious?",
        th:"เคยไหม ที่แก้ปัญหาด้วยวิธีไม่คาดคิด แล้วถูกบอกทีหลังว่ามันชัดเจนอยู่แล้ว?" },
  58: { en:"Have you ever felt happiest just before something bad, and saddest just before something good?",
        th:"เคยไหม ที่สุขที่สุดก่อนเรื่องร้ายมาถึง และเศร้าที่สุดก่อนเรื่องดีจะเริ่ม?" },
  59: { en:"Have you ever spent less than people expected, and gained more than they thought possible?",
        th:"เคยไหม ที่ใช้จ่ายน้อยกว่าที่คนรอบตัวคาดหวัง แล้วได้กลับมามากกว่าที่ใครคิดว่าเป็นไปได้?" },
  60: { en:"Have you ever managed a team well by managing yourself out of the way?",
        th:"เคยไหม ที่จัดการทีมได้ดี ด้วยการจัดการตัวเองให้ออกไปจากทาง?" },
  61: { en:"Have you ever made yourself the smallest one in the room, and watched everyone come to you?",
        th:"เคยไหม ที่ทำตัวให้เป็นคนตัวเล็กที่สุดในห้อง แล้วทุกคนกลับเดินมาหา?" },
  62: { en:"Have you ever realized the answer was hiding in plain sight in a place you'd already walked past a hundred times?",
        th:"เคยไหม ที่รู้ว่าคำตอบซ่อนอยู่ตรงที่คุณเดินผ่านมาเป็นร้อยรอบแล้ว?" },
  63: { en:"Have you ever ignored a small problem for so long that it became a large one, then had to do the small fix anyway?",
        th:"เคยไหม ที่ปล่อยปัญหาเล็ก ๆ จนมันใหญ่ แล้วสุดท้ายก็ต้องทำการแก้แบบเล็ก ๆ นั่นเอง?" },
  64: { en:"Have you ever started a thousand-mile journey and felt the only hard part was taking the first step?",
        th:"เคยไหม ที่เริ่มเดินทางพันลี้ แล้วพบว่าส่วนยากที่สุดคือก้าวแรก?" },
  65: { en:"Have you ever met a wise person who looked, somehow, simpler than you expected?",
        th:"เคยไหม ที่เจอคนฉลาด แล้วเขาดูเรียบง่ายกว่าที่คุณคิดไว้?" },
  66: { en:"Have you ever followed someone who placed themselves below you on purpose?",
        th:"เคยไหม ที่ตามคนที่จงใจวางตัวเองไว้ต่ำกว่าคุณ?" },
  67: { en:"Have you ever protected someone you love, and discovered courage you didn't know you had?",
        th:"เคยไหม ที่ปกป้องคนที่รัก แล้วค้นพบความกล้าหาญที่คุณไม่รู้ว่ามีอยู่ในตัว?" },
  68: { en:"Have you ever ended a fight without throwing a punch?",
        th:"เคยไหม ที่จบการทะเลาะได้โดยไม่ต้องเหวี่ยงหมัดสักครั้ง?" },
  69: { en:"Have you ever entered a room as a guest and left as a host?",
        th:"เคยไหม ที่เข้าห้องหนึ่งในฐานะแขก แล้วออกมาในฐานะเจ้าบ้าน?" },
  70: { en:"Have you ever said something simple, true, and obvious — and watched no one understand it?",
        th:"เคยไหม ที่พูดสิ่งที่ง่าย จริง และชัดเจน แล้วไม่มีใครเข้าใจ?" },
  71: { en:"Have you ever felt completely sure of something, and later realized that certainty was the whole problem?",
        th:"เคยไหม ที่มั่นใจในอะไรเต็มที่ แล้วต่อมารู้ว่าความมั่นใจนั่นเองคือปัญหาทั้งหมด?" },
  72: { en:"Have you ever stopped being afraid of an authority — and felt the floor under your feet shift?",
        th:"เคยไหม ที่หยุดกลัวอำนาจ แล้วพื้นใต้เท้าก็พลอยเปลี่ยนไป?" },
  73: { en:"Have you ever escaped one consequence and run straight into a quieter, larger one?",
        th:"เคยไหม ที่หนีผลลัพธ์หนึ่งได้ แล้ววิ่งเข้าหาผลลัพธ์ที่เงียบกว่าและใหญ่กว่า?" },
  74: { en:"Have you ever wanted to punish someone, and known — somewhere — that wasn't actually your job?",
        th:"เคยไหม ที่อยากลงโทษใคร แล้วในใจรู้ลึก ๆ ว่ามันไม่ใช่หน้าที่ของคุณ?" },
  75: { en:"Have you ever been hungry in a country whose elite were extravagantly full?",
        th:"เคยไหม ที่หิวอยู่ในประเทศที่ชนชั้นบนกินอิ่มเกินพอดี?" },
  76: { en:"Have you ever met someone old who was softer than someone young — and stronger?",
        th:"เคยไหม ที่เจอคนแก่ที่อ่อนกว่าคนหนุ่ม — และแข็งแรงกว่าด้วย?" },
  77: { en:"Have you ever seen a system take from those with too much and give to those with too little, and recognised it as natural?",
        th:"เคยไหม ที่เห็นระบบหนึ่งเอาจากคนที่มีมากเกินมาให้คนที่มีน้อยเกิน แล้วเห็นว่ามันเป็นธรรมชาติ?" },
  78: { en:"Have you ever watched water reshape stone, and known you were watching a strategy?",
        th:"เคยไหม ที่เห็นน้ำเปลี่ยนรูปหิน แล้วรู้ว่าคุณกำลังดูยุทธศาสตร์อยู่?" },
  79: { en:"Have you ever 'settled' a quarrel and felt a small ache where the settlement was supposed to be?",
        th:"เคยไหม ที่ \"ตกลง\" เรื่องทะเลาะกันได้ แล้วยังรู้สึกเจ็บเบา ๆ ตรงที่น่าจะหายดีแล้ว?" },
  80: { en:"Have you ever visited a small village and felt, for one afternoon, that this was all anyone really needed?",
        th:"เคยไหม ที่ไปเยือนหมู่บ้านเล็ก ๆ แล้วรู้สึกชั่วบ่ายหนึ่งว่า แค่นี้ก็พอแล้วสำหรับชีวิต?" },
  81: { en:"Have you ever read the last line of a book and known the only honest move was to start it again?",
        th:"เคยไหม ที่อ่านบรรทัดสุดท้ายของหนังสือเล่มหนึ่ง แล้วรู้ว่าทางเดียวที่ซื่อสัตย์คือเปิดอ่านใหม่ตั้งแต่ต้น?" }
};
