/* =============================================================
   CLOSING QUESTIONS — 問 wèn
   At the end of every chapter, one question that almost anyone
   has felt. Trilingual. Direct. Recognisable. The "have you ever"
   moment that makes the chapter land in the body, not just the head.
   ============================================================ */
window.CLOSERS = {
  1:  { en:"Have you ever tried to explain something you love, only to feel every word make it smaller?",
        th:"เคยไหม ที่พยายามอธิบายสิ่งที่คุณรักให้ใครฟัง แล้วพบว่าทุกคำที่หลุดออกไปทำให้มันเล็กลง?",
        cn:"你有没有试过解释一样你爱的东西，却发现每一个字都让它变得更小？" },
  2:  { en:"Have you ever called something beautiful, and immediately noticed what was ugly right next to it?",
        th:"เคยไหม ที่เพิ่งเรียกอะไรว่าสวย แล้วทันใดนั้นก็เห็นความน่าเกลียดที่อยู่ข้าง ๆ?",
        cn:"你有没有叫过什么东西美，然后立刻注意到它旁边就有什么丑的东西？" },
  3:  { en:"Have you ever caught yourself wanting something only because someone else was holding it up?",
        th:"เคยไหม ที่จับได้ว่าตัวเองอยากได้บางอย่าง เพียงเพราะมีคนชูมันขึ้นมาให้ดู?",
        cn:"你有没有发现自己想要某样东西，仅仅是因为有人把它举起来给你看？" },
  4:  { en:"Have you ever found a quiet room more useful, somehow, than a full one?",
        th:"เคยไหม ที่รู้สึกว่าห้องที่ว่างเปล่ากลับมีประโยชน์ มากกว่าห้องที่อัดแน่นไปด้วยของ?",
        cn:"你有没有觉得一个空的房间，不知怎的比一个满的房间更有用？" },
  5:  { en:"Have you ever felt better the moment you stopped taking it personally?",
        th:"เคยไหม ที่รู้สึกดีขึ้นทันที ในวินาทีที่หยุดคิดว่าเรื่องนี้เกิดขึ้นเพื่อจะทำร้ายคุณ?",
        cn:"你有没有在停止把它当成针对你的那一刻，突然感觉好多了？" },
  6:  { en:"Have you ever been the listener in the room — and noticed you were the one who got remembered?",
        th:"เคยไหม ที่เป็นคนฟังในห้องนั้น แล้วพบว่าตัวเองคือคนที่คนอื่นจำได้?",
        cn:"你有没有做过房间里那个听的人——然后发现你才是被记住的那个？" },
  7:  { en:"Have you ever lost track of yourself doing work that mattered, and felt strangely whole afterwards?",
        th:"เคยไหม ที่ทำงานสำคัญจนลืมตัวเอง แล้วเสร็จออกมาแล้วกลับรู้สึกเป็นตัวเองมากกว่าเดิม?",
        cn:"你有没有在做有意义的工作时忘了自己，然后事后感到一种奇怪的完整？" },
  8:  { en:"Have you ever pushed back against someone you love — and noticed you were the only one bruised?",
        th:"เคยไหม ที่ดันสู้กับคนที่คุณรัก แล้วสุดท้ายคนที่ฟกช้ำคือตัวคุณคนเดียว?",
        cn:"你有没有在不想赢的时候，反而做得最好？" },
  9:  { en:"Have you ever tried so hard to reach something and missed it, then later got it just by sitting still?",
        th:"เคยไหม ที่พยายามเท่าไรก็ไปไม่ถึง แต่บางครั้ง อยู่เฉย ๆ ก็ได้สิ่งที่อยากได้มาเอง?",
        cn:"你有没有在停下来的那一刻，才意识到自己其实早就该停了？" },
  10: { en:"Have you ever held your breath in a hard moment, then felt the moment pass the second you let it go?",
        th:"เคยไหม ที่กลั้นหายใจในจังหวะยาก ๆ แล้ววินาทีที่ปล่อยลม ทุกอย่างก็คลี่คลายเอง?",
        cn:"你有没有在困难的时刻屏住呼吸，然后在你放手的那一秒，感觉到那一刻过去了？" },
  11: { en:"Have you ever loved a room not for its furniture, but for the empty space between the furniture?",
        th:"เคยไหม ที่รักห้องห้องหนึ่ง ไม่ใช่เพราะเฟอร์นิเจอร์ แต่เพราะที่ว่างระหว่างเฟอร์นิเจอร์?",
        cn:"你有没有爱过一个房间，不是因为它的家具，而是因为家具之间的空隙？" },
  12: { en:"Have you ever bought something that looked perfect online, and felt nothing the moment it arrived?",
        th:"เคยไหม ที่ซื้อของที่ดูเพอร์เฟกต์ในออนไลน์ แล้วตอนของมาถึงบ้าน กลับไม่รู้สึกอะไรเลย?",
        cn:"你有没有买过一样在网上看起来完美的东西，却在它到达的那一刻感到什么都没有？" },
  13: { en:"Have you ever felt nervous waiting for praise — and just as nervous waiting for blame?",
        th:"เคยไหม ที่ใจสั่นรอคำชม แล้วก็ใจสั่นเหมือนกันรอคำตำหนิ?",
        cn:"你有没有因为太过在意别人的眼光，而忘了自己真正想要什么？" },
  14: { en:"Have you ever sensed something important in the room without quite being able to point at it?",
        th:"เคยไหม ที่รู้สึกว่ามีอะไรสำคัญอยู่ในห้อง โดยไม่สามารถชี้ออกมาได้เลยว่ามันคืออะไร?",
        cn:"你有没有试过追逐一个影子，然后发现它跑得比你还快？" },
  15: { en:"Have you ever watched someone move through a hard moment so quietly you barely noticed it was hard?",
        th:"เคยไหม ที่เห็นใครสักคนผ่านช่วงที่ยากลำบากอย่างเงียบ ๆ จนคุณเกือบไม่รู้ตัวว่ามันยาก?",
        cn:"你有没有遇到过一个人，他什么都不做，只是在那里，却让你感到一切都好？" },
  16: { en:"Have you ever come back from a long walk with the answer you'd been chasing at your desk?",
        th:"เคยไหม ที่กลับจากการเดินยาว ๆ พร้อมคำตอบที่นั่งหาที่โต๊ะทำงานเป็นชั่วโมงไม่เจอ?",
        cn:"你有没有在安静下来之后，才发现自己一直在找的东西其实一直在里面？" },
  17: { en:"Have you ever worked under a leader you barely noticed — and only realized they were good after they left?",
        th:"เคยไหม ที่ทำงานกับผู้นำที่คุณแทบไม่สังเกต แล้วเพิ่งรู้ว่าเขาเก่ง ตอนเขาไปแล้ว?",
        cn:"你有没有因为某个领导什么都不说，反而觉得他最值得信任？" },
  18: { en:"Have you ever noticed that the words 'integrity' and 'transparency' got loud the moment they got rare?",
        th:"เคยไหม ที่สังเกตว่าคำว่า \"คุณธรรม\" และ \"ความโปร่งใส\" ดังขึ้นพอดี ในยุคที่มันหายาก?",
        cn:"你有没有发现，当一种道德需要被大声宣扬的时候，它其实已经不存在了？" },
  19: { en:"Have you ever felt better in a country with fewer rules, even though you couldn't say why?",
        th:"เคยไหม ที่รู้สึกดีขึ้นในที่ที่กฎน้อยลง แม้คุณบอกไม่ได้ว่าเพราะอะไร?",
        cn:"你有没有因为什么都不想要，反而得到了最多？" },
  20: { en:"Have you ever felt out of step with everyone at the party, and quietly known you were not wrong?",
        th:"เคยไหม ที่รู้สึกไม่เข้าจังหวะกับใครเลยในงานเลี้ยง และในใจก็รู้ว่าตัวคุณไม่ได้ผิด?",
        cn:"你有没有在所有人都兴奋的时候，觉得自己是唯一一个冷静的人？" },
  21: { en:"Have you ever met someone whose virtue you couldn't quite name, only feel?",
        th:"เคยไหม ที่เจอใครสักคน ซึ่งคุณรู้สึกได้ถึงคุณธรรมของเขา โดยที่บอกไม่ออกว่ามันคือคุณธรรมข้อไหน?",
        cn:"你有没有在完全放松的时候，感到一种比努力时更深的真实？" },
  22: { en:"Have you ever bent — and noticed the storm broke around you instead of breaking you?",
        th:"เคยไหม ที่ยอมโค้งให้สถานการณ์ แล้วพบว่าพายุพัดผ่านไปโดยไม่หักคุณ?",
        cn:"你有没有因为不想争第一，反而成了唯一一个到达终点的人？" },
  23: { en:"Have you ever tried to force a conversation, and watched it die in your hands?",
        th:"เคยไหม ที่พยายามฝืนให้บทสนทนาเดินต่อ แล้วดูมันตายในมือคุณเอง?",
        cn:"你有没有在大自然面前感到一种不需要语言的理解？" },
  24: { en:"Have you ever stood on tiptoes for someone, and felt your knees give out?",
        th:"เคยไหม ที่เขย่งปลายเท้าให้ใคร แล้วเข่าตัวเองอ่อนทรุดลง?",
        cn:"你有没有因为想让自己看起来比别人好，反而让自己变得很小？" },
  25: { en:"Have you ever felt that something was right not because someone said so, but because it just was?",
        th:"เคยไหม ที่รู้สึกว่าบางอย่างถูก ไม่ใช่เพราะใครบอก แต่เพราะมันถูกของมันเอง?",
        cn:"你有没有在不知道一样东西的名字的时候，反而更清楚地感受到它的存在？" },
  26: { en:"Have you ever felt safer with someone who was calm than with someone who was correct?",
        th:"เคยไหม ที่รู้สึกปลอดภัยกับคนที่นิ่ง มากกว่ากับคนที่ถูกต้อง?",
        cn:"你有没有因为紧紧抓住什么，反而让它更快地溜走？" },
  27: { en:"Have you ever been helped by someone who left so little trace, you forgot to thank them?",
        th:"เคยไหม ที่มีคนช่วยคุณโดยทิ้งร่องรอยไว้น้อยมาก จนคุณลืมขอบคุณเขา?",
        cn:"你有没有帮助过一个人，然后让他以为那是他自己做到的？" },
  28: { en:"Have you ever lost an argument by winning it?",
        th:"เคยไหม ที่แพ้ศึกใดศึกหนึ่งโดยการชนะมัน?",
        cn:"你有没有回到一个你以为已经离开的地方，却发现它一直在等你？" },
  29: { en:"Have you ever tried to grip something tighter, and felt it slip away faster?",
        th:"เคยไหม ที่ยิ่งกำสิ่งใดให้แน่นขึ้น มันยิ่งหลุดมือคุณเร็วขึ้น?",
        cn:"你有没有因为想要改变一切，反而让一切都变得更糟？" },
  30: { en:"Have you ever taken a swing at a problem and watched the bruise come back to you?",
        th:"เคยไหม ที่เหวี่ยงหมัดใส่ปัญหา แล้วรอยช้ำกลับมาที่ตัวคุณเอง?",
        cn:"你有没有在用力量解决问题之后，发现力量本身就是问题？" },
  31: { en:"Have you ever 'won' a fight and felt strangely heavier afterwards?",
        th:"เคยไหม ที่ \"ชนะ\" การทะเลาะแล้วรู้สึกหนักอกมากกว่าเดิม?",
        cn:"你有没有在不需要武器的时候，感到最安全？" },
  32: { en:"Have you ever met someone whose silence said more than anyone else's argument?",
        th:"เคยไหม ที่เจอคนซึ่งความเงียบของเขาบอกอะไรได้มากกว่า การถกเถียงของใครทั้งหมด?",
        cn:"你有没有因为不试图去控制一样东西，反而最自由地使用了它？" },
  33: { en:"Have you ever known a thousand things about other people, and almost nothing about yourself?",
        th:"เคยไหม ที่รู้เรื่องคนอื่นเป็นพัน แต่แทบไม่รู้อะไรเกี่ยวกับตัวเองเลย?",
        cn:"你有没有在认识了自己之后，才发现你其实不需要去任何地方？" },
  34: { en:"Have you ever helped someone in a way they never noticed, and felt that was the cleanest help you ever gave?",
        th:"เคยไหม ที่ช่วยใครโดยที่เขาไม่รู้ตัว แล้วรู้สึกว่ามันคือการช่วยที่สะอาดที่สุดที่เคยทำ?",
        cn:"你有没有因为不追求伟大，反而最伟大的事情通过你发生了？" },
  35: { en:"Have you ever held a steady tune in a noisy room, and watched everyone slowly come to listen?",
        th:"เคยไหม ที่ฮัมเพลงเงียบ ๆ ในห้องที่อึกทึก แล้วเห็นทุกคนค่อย ๆ หันมาฟัง?",
        cn:"你有没有在接近危险的时候，感到一种奇怪的平静？" },
  36: { en:"Have you ever let something rise so it could fall on its own?",
        th:"เคยไหม ที่ปล่อยให้บางอย่างขึ้นไปสุด เพื่อให้มันร่วงลงเองตามแรงโน้มถ่วงของมัน?",
        cn:"你有没有因为让某样东西变小，反而让它变得更强？" },
  37: { en:"Have you ever stopped meddling and watched the thing you were managing run perfectly fine without you?",
        th:"เคยไหม ที่หยุดยุ่งกับมัน แล้วเห็นสิ่งที่คุณจัดการอยู่เดินไปได้ดีโดยไม่มีคุณ?",
        cn:"你有没有在停止刻意去做的时候，事情反而自己完成了？" },
  38: { en:"Have you ever felt ESG reports louder than the goodness they were supposed to track?",
        th:"เคยไหม ที่รู้สึกว่ารายงานความยั่งยืนเสียงดังกว่าความดีที่มันบอกว่ากำลังวัดอยู่?",
        cn:"你有没有因为不想表现得有道德，反而最有道德？" },
  39: { en:"Have you ever felt held together by one thread you couldn't quite name?",
        th:"เคยไหม ที่รู้สึกว่าตัวเองถูกยึดไว้ด้วยเส้นด้ายเส้นเดียวที่คุณบอกชื่อไม่ออก?",
        cn:"你有没有因为不想变得特别，反而变得最特别？" },
  40: { en:"Have you ever come back to a place you left, and recognised it as forward progress?",
        th:"เคยไหม ที่กลับไปยังที่ที่จากมา แล้วรับรู้ว่ามันคือการก้าวไปข้างหน้า?",
        cn:"你有没有在一切都走向结束的地方，看到了新的开始？" },
  41: { en:"Have you ever laughed at advice that, ten years later, turned out to be exactly right?",
        th:"เคยไหม ที่หัวเราะคำแนะนำของใคร แล้วสิบปีต่อมารู้ว่ามันถูกที่สุด?",
        cn:"你有没有因为听不见某种声音，反而更清楚地听到了它？" },
  42: { en:"Have you ever felt that your shadow was as much a part of you as your face?",
        th:"เคยไหม ที่รู้สึกว่าเงาของคุณเป็นส่วนหนึ่งของคุณ พอ ๆ กับใบหน้า?",
        cn:"你有没有在失去一样东西的时候，发现你从来没有真正拥有过它？" },
  43: { en:"Have you ever watched water find a way through stone over time, and recognised yourself in it?",
        th:"เคยไหม ที่เห็นน้ำหาทางผ่านหินไปได้เมื่อเวลาผ่าน แล้วเห็นตัวเองในนั้น?",
        cn:"你有没有用最软的东西，穿透了最硬的东西？" },
  44: { en:"Have you ever finally had everything you said you wanted, and felt nothing in particular?",
        th:"เคยไหม ที่ในที่สุดก็มีทุกอย่างที่เคยบอกว่าอยากได้ แล้วกลับไม่รู้สึกอะไรเป็นพิเศษ?",
        cn:"你有没有因为不想占有，反而永远不会失去？" },
  45: { en:"Have you ever loved a piece of art precisely because of where the artist stopped working?",
        th:"เคยไหม ที่หลงรักงานศิลปะ เพราะตรงที่ศิลปินตัดสินใจหยุดมือ?",
        cn:"你有没有在承认你不知道的时候，反而最接近知道？" },
  46: { en:"Have you ever felt the thing you were chasing go quieter the moment you stopped chasing it?",
        th:"เคยไหม ที่สิ่งที่คุณไล่ตามเงียบลง ในวินาทีที่คุณหยุดไล่ตามมัน?",
        cn:"你有没有因为欲望太多，反而离满足越来越远？" },
  47: { en:"Have you ever known what was going on in a room without leaving your chair?",
        th:"เคยไหม ที่รู้ว่ามีอะไรกำลังเกิดขึ้นในห้องนั้น โดยไม่ลุกจากเก้าอี้?",
        cn:"你有没有在没有出门的时候，却看到了整个世界？" },
  48: { en:"Have you ever done less, on purpose, and gotten more done?",
        th:"เคยไหม ที่ตั้งใจทำน้อยลง แล้วงานเสร็จมากขึ้น?",
        cn:"你有没有在学得越来越少的时候，反而懂得越来越多？" },
  49: { en:"Have you ever met someone who treated everyone like a friend, and noticed strangers became their friends?",
        th:"เคยไหม ที่เจอคนซึ่งปฏิบัติต่อทุกคนราวกับเพื่อน แล้วเห็นคนแปลกหน้ากลายเป็นเพื่อนของเขา?",
        cn:"你有没有在对好人坏人没有分别心的时候，反而最公平？" },
  50: { en:"Have you ever felt how thin the wall between life and death is, in a perfectly ordinary moment?",
        th:"เคยไหม ที่รู้สึกว่ากำแพงระหว่างความเป็นกับความตายบางมาก ในวินาทีธรรมดา ๆ?",
        cn:"你有没有在出生的时候，就已经准备好面对死亡？" },
  51: { en:"Have you ever raised someone or something well by getting out of its way?",
        th:"เคยไหม ที่เลี้ยงดูใครหรืออะไรได้ดี โดยการถอยออกห่างจากมัน?",
        cn:"你有没有因为不试图去滋养，反而滋养了一切？" },
  52: { en:"Have you ever traced a problem back to its mother, and watched the children solve themselves?",
        th:"เคยไหม ที่สาวปัญหากลับไปหารากของมัน แล้วเห็นปลายทางคลี่คลายเอง?",
        cn:"你有没有在回到起点的时候，才发现你从未离开过？" },
  53: { en:"Have you ever passed a beautifully dressed person and felt, instinctively, that something was off?",
        th:"เคยไหม ที่เดินผ่านคนแต่งตัวสวยมาก แล้วสัญชาตญาณบอกคุณว่ามีบางอย่างไม่ใช่?",
        cn:"你有没有因为走了一条看起来好的路，反而迷失了？" },
  54: { en:"Have you ever fixed something tiny in yourself, and noticed your whole household ease?",
        th:"เคยไหม ที่แก้สิ่งเล็ก ๆ ในตัวเอง แล้วทั้งบ้านพลอยผ่อนคลายตาม?",
        cn:"你有没有因为不想被看见，反而被看见了？" },
  55: { en:"Have you ever envied a child's softness — and known it was strength, not weakness?",
        th:"เคยไหม ที่อิจฉาความอ่อนของเด็กเล็ก และรู้ว่ามันคือความแข็งแรง ไม่ใช่ความอ่อนแอ?",
        cn:"你有没有因为不想伤害任何东西，反而拥有了真正的力量？" },
  56: { en:"Have you ever stopped composing your reply mid-sentence, and noticed the conversation become real?",
        th:"เคยไหม ที่หยุดเรียบเรียงคำตอบกลางประโยค แล้วบทสนทนาเริ่มเป็นของจริง?",
        cn:"你有没有因为知道得太多，反而说不出话来？" },
  57: { en:"Have you ever solved something by doing the unexpected thing, only to be told afterwards it was obvious?",
        th:"เคยไหม ที่แก้ปัญหาด้วยวิธีไม่คาดคิด แล้วถูกบอกทีหลังว่ามันชัดเจนอยู่แล้ว?",
        cn:"你有没有因为规矩太多，反而让事情变得更乱？" },
  58: { en:"Have you ever felt happiest just before something bad, and saddest just before something good?",
        th:"เคยไหม ที่สุขที่สุดก่อนเรื่องร้ายมาถึง และเศร้าที่สุดก่อนเรื่องดีจะเริ่ม?",
        cn:"你有没有因为不想改变什么，反而让一切都变好了？" },
  59: { en:"Have you ever spent less than people expected, and gained more than they thought possible?",
        th:"เคยไหม ที่ใช้จ่ายน้อยกว่าที่คนรอบตัวคาดหวัง แล้วได้กลับมามากกว่าที่ใครคิดว่าเป็นไปได้?",
        cn:"你有没有在节俭的时候，反而拥有了最多？" },
  60: { en:"Have you ever managed a team well by managing yourself out of the way?",
        th:"เคยไหม ที่จัดการทีมได้ดี ด้วยการจัดการตัวเองให้ออกไปจากทาง?",
        cn:"你有没有在不用力的时候，反而处理好了最难的事？" },
  61: { en:"Have you ever made yourself the smallest one in the room, and watched everyone come to you?",
        th:"เคยไหม ที่ทำตัวให้เป็นคนตัวเล็กที่สุดในห้อง แล้วทุกคนกลับเดินมาหา?",
        cn:"你有没有因为把自己放得很低，反而被所有人尊重？" },
  62: { en:"Have you ever realized the answer was hiding in plain sight in a place you'd already walked past a hundred times?",
        th:"เคยไหม ที่รู้ว่าคำตอบซ่อนอยู่ตรงที่คุณเดินผ่านมาเป็นร้อยรอบแล้ว?",
        cn:"你有没有在迷路的时候，才发现最美的风景？" },
  63: { en:"Have you ever ignored a small problem for so long that it became a large one, then had to do the small fix anyway?",
        th:"เคยไหม ที่ปล่อยปัญหาเล็ก ๆ จนมันใหญ่ แล้วสุดท้ายก็ต้องทำการแก้แบบเล็ก ๆ นั่นเอง?",
        cn:"你有没有因为把事情看得很小，反而做成了大事？" },
  64: { en:"Have you ever started a thousand-mile journey and felt the only hard part was taking the first step?",
        th:"เคยไหม ที่เริ่มเดินทางพันลี้ แล้วพบว่าส่วนยากที่สุดคือก้าวแรก?",
        cn:"你有没有在事情还没开始的时候，就已经知道怎么结束它？" },
  65: { en:"Have you ever met a wise person who looked, somehow, simpler than you expected?",
        th:"เคยไหม ที่เจอคนฉลาด แล้วเขาดูเรียบง่ายกว่าที่คุณคิดไว้?",
        cn:"你有没有因为不想让人知道太多，反而让人明白了一切？" },
  66: { en:"Have you ever followed someone who placed themselves below you on purpose?",
        th:"เคยไหม ที่ตามคนที่จงใจวางตัวเองไว้ต่ำกว่าคุณ?",
        cn:"你有没有因为不想当老大，反而成了最好的老大？" },
  67: { en:"Have you ever protected someone you love, and discovered courage you didn't know you had?",
        th:"เคยไหม ที่ปกป้องคนที่รัก แล้วค้นพบความกล้าหาญที่คุณไม่รู้ว่ามีอยู่ในตัว?",
        cn:"你有没有因为不够勇敢，反而做了最勇敢的事？" },
  68: { en:"Have you ever ended a fight without throwing a punch?",
        th:"เคยไหม ที่จบการทะเลาะได้โดยไม่ต้องเหวี่ยงหมัดสักครั้ง?",
        cn:"你有没有因为不想争，反而赢了最重要的那一局？" },
  69: { en:"Have you ever entered a room as a guest and left as a host?",
        th:"เคยไหม ที่เข้าห้องหนึ่งในฐานะแขก แล้วออกมาในฐานะเจ้าบ้าน?",
        cn:"你有没有在退后的时候，反而发现那才是真正的前进？" },
  70: { en:"Have you ever said something simple, true, and obvious — and watched no one understand it?",
        th:"เคยไหม ที่พูดสิ่งที่ง่าย จริง และชัดเจน แล้วไม่มีใครเข้าใจ?",
        cn:"你有没有因为不被理解，反而知道自己是走在对的路上？" },
  71: { en:"Have you ever felt completely sure of something, and later realized that certainty was the whole problem?",
        th:"เคยไหม ที่มั่นใจในอะไรเต็มที่ แล้วต่อมารู้ว่าความมั่นใจนั่นเองคือปัญหาทั้งหมด?",
        cn:"你有没有在知道自己不知道的时候，反而最接近智慧？" },
  72: { en:"Have you ever stopped being afraid of an authority — and felt the floor under your feet shift?",
        th:"เคยไหม ที่หยุดกลัวอำนาจ แล้วพื้นใต้เท้าก็พลอยเปลี่ยนไป?",
        cn:"你有没有因为不想控制别人，反而让所有人都愿意跟着你？" },
  73: { en:"Have you ever escaped one consequence and run straight into a quieter, larger one?",
        th:"เคยไหม ที่หนีผลลัพธ์หนึ่งได้ แล้ววิ่งเข้าหาผลลัพธ์ที่เงียบกว่าและใหญ่กว่า?",
        cn:"你有没有因为不想杀人，反而救了最多的人？" },
  74: { en:"Have you ever wanted to punish someone, and known — somewhere — that wasn't actually your job?",
        th:"เคยไหม ที่อยากลงโทษใคร แล้วในใจรู้ลึก ๆ ว่ามันไม่ใช่หน้าที่ของคุณ?",
        cn:"你有没有发现，那些叫得最响的规则，往往是最不公平的？" },
  75: { en:"Have you ever been hungry in a country whose elite were extravagantly full?",
        th:"เคยไหม ที่หิวอยู่ในประเทศที่ชนชั้นบนกินอิ่มเกินพอดี?",
        cn:"你有没有因为不想被喂饱，反而真正吃饱了？" },
  76: { en:"Have you ever met someone old who was softer than someone young — and stronger?",
        th:"เคยไหม ที่เจอคนแก่ที่อ่อนกว่าคนหนุ่ม — และแข็งแรงกว่าด้วย?",
        cn:"你有没有在变硬的时候，感到自己正在死去？" },
  77: { en:"Have you ever seen a system take from those with too much and give to those with too little, and recognised it as natural?",
        th:"เคยไหม ที่เห็นระบบหนึ่งเอาจากคนที่มีมากเกินมาให้คนที่มีน้อยเกิน แล้วเห็นว่ามันเป็นธรรมชาติ?",
        cn:"你有没有因为不想多拿，反而拥有了最多？" },
  78: { en:"Have you ever watched water reshape stone, and known you were watching a strategy?",
        th:"เคยไหม ที่เห็นน้ำเปลี่ยนรูปหิน แล้วรู้ว่าคุณกำลังดูยุทธศาสตร์อยู่?",
        cn:"你有没有用最弱的东西，战胜了最强的东西？" },
  79: { en:"Have you ever 'settled' a quarrel and felt a small ache where the settlement was supposed to be?",
        th:"เคยไหม ที่ \"ตกลง\" เรื่องทะเลาะกันได้ แล้วยังรู้สึกเจ็บเบา ๆ ตรงที่น่าจะหายดีแล้ว?",
        cn:"你有没有在不想报复的时候，反而真正解决了问题？" },
  80: { en:"Have you ever visited a small village and felt, for one afternoon, that this was all anyone really needed?",
        th:"เคยไหม ที่ไปเยือนหมู่บ้านเล็ก ๆ แล้วรู้สึกชั่วบ่ายหนึ่งว่า แค่นี้ก็พอแล้วสำหรับชีวิต?",
        cn:"你有没有在一个很小的地方，反而感到最自由？" },
  81: { en:"Have you ever read the last line of a book and known the only honest move was to start it again?",
        th:"เคยไหม ที่อ่านบรรทัดสุดท้ายของหนังสือเล่มหนึ่ง แล้วรู้ว่าทางเดียวที่ซื่อสัตย์คือเปิดอ่านใหม่ตั้งแต่ต้น?",
        cn:"你有没有在不想占有的时候，反而最富有？" }
};
