window.REFERENCE_LIBRARY = [
  { slug:'tsai-dao-de-jing', cover:'reference-covers/tsai-dao-de-jing.jpg', title:'Dao De Jing: The Illustrated Library of Chinese Classics', author:'Laozi, adapted and illustrated by C. C. Tsai; translated by Brian Bruya', kind:'comic classic', right:'Tsai gets the pedagogy right: the Dao De Jing becomes memorable because a paradox turns into a face, a gesture, a foolish official, a cup, a river, a bowed tree.', wrong:'It necessarily simplifies. Some metaphysical and philological tensions disappear because comics need a scene.', why:'I read Tsai because he taught more people to approach Chinese classics without fear than almost anyone alive.' },
  { slug:'slingerland-trying-not-to-try', cover:'reference-covers/slingerland-trying-not-to-try.jpg', title:'Trying Not to Try', author:'Edward Slingerland', kind:'scholarship + cognitive science', right:'The best bridge in the genre: wu-wei is not laziness but trained spontaneity, where deliberate practice becomes embodied ease.', wrong:'The pop-science frame can make early Chinese debates look tidier than they were.', why:'This is the book I trust when explaining why Daoism is practical psychology, not incense and vagueness.' },
  { slug:'slingerland-ch2', cover:'reference-covers/slingerland-ch2.jpg', title:'Trying Not to Try, chapter 2 excerpt', author:'Edward Slingerland', kind:'wu-wei / de', right:'Excellent on de as charismatic power: the signal you cannot fake because faking it destroys it.', wrong:'A short excerpt cannot carry the whole Warring States argumentative world.', why:'I return to this whenever a chapter talks about virtue, leadership, or effortless authority.' },
  { slug:'slingerland-ch4', cover:'reference-covers/slingerland-ch4.jpg', title:'Trying Not to Try, chapter 4 excerpt', author:'Edward Slingerland', kind:'effort paradox', right:'Clarifies the paradox of forcing naturalness: you train the conditions, not the spontaneity itself.', wrong:'The laboratory analogy can underplay the ritual and political stakes.', why:'It is the cleanest explanation of why “try harder to relax” fails.' },
  { slug:'slingerland-ch6', cover:'reference-covers/slingerland-ch6.jpg', title:'Trying Not to Try, chapter 6 excerpt', author:'Edward Slingerland', kind:'flow / cognition', right:'Strong on flow, hot cognition, and the body taking over after long training.', wrong:'Flow is adjacent to Daoism, not identical to it.', why:'It gives modern psychological vocabulary for something Laozi and Zhuangzi felt their way toward.' },
  { slug:'jonathan-star', cover:'reference-covers/jonathan-star.jpg', title:'Tao Te Ching: The Definitive Edition', author:'Jonathan Star', kind:'translation + source matrix', right:'Useful because it exposes translation choice. You can see how many English Daos are being made from the same Chinese.', wrong:'The “definitive” posture is too confident for a text whose first sentence warns against definitive speech.', why:'I read it as a comparison machine, not as a final authority.' },
  { slug:'stephen-mitchell', cover:'reference-covers/stephen-mitchell.jpg', title:'Tao Te Ching', author:'Stephen Mitchell', kind:'poetic adaptation', right:'Beautiful, lucid, and responsible for bringing many readers into the room.', wrong:'Often too smooth. It turns rough Chinese argument into modern spiritual poetry.', why:'I read it because influence matters; many English readers are really responding to Mitchell’s Laozi.' },
  { slug:'derek-lin', cover:'reference-covers/derek-lin.jpg', title:'Tao Te Ching: Annotated and Explained', author:'Derek Lin', kind:'practical commentary', right:'Clear, grounded, and good at everyday moral application.', wrong:'Can domesticate the strangeness too quickly.', why:'Useful when I want the chapter to become conduct rather than atmosphere.' },
  { slug:'holmes-welch', cover:'reference-covers/holmes-welch.jpg', title:'The Parting of the Way', author:'Holmes Welch', kind:'Daoist history', right:'Excellent for separating philosophical Daoism, religious Daoism, and modern fantasy versions.', wrong:'Older scholarship carries some period assumptions and can sound too neat now.', why:'I read Welch to keep Laozi connected to actual Chinese religious history.' },
  { slug:'laotzestaotehkin', cover:'reference-covers/laotzestaotehkin.jpg', title:'Tao Teh King', author:'Laozi, older public-domain English edition', kind:'historical translation', right:'Shows the Victorian/early modern English Laozi: solemn, biblical, and influential.', wrong:'Often stiff and Orientalist in tone.', why:'I read old translations to understand the genealogy of English misunderstandings.' },
  { slug:'zhuangzi-way-of-nature', cover:'reference-covers/zhuangzi-way-of-nature.jpg', title:'The Way of Nature', author:'Zhuangzi, adapted and illustrated by C. C. Tsai', kind:'parallel Daoist comic', right:'Shows the Zhuangzi side of Daoism: freer, funnier, more suspicious of categories.', wrong:'Not Laozi, so it should illuminate rather than replace the Dao De Jing.', why:'I use it when Laozi needs a story, not another abstract sentence.' },
  { slug:'zhuangzi-speaks', cover:'reference-covers/zhuangzi-speaks.jpg', title:'Zhuangzi Speaks: The Music of Nature', author:'C. C. Tsai', kind:'parallel classic', right:'Best at showing how Daoism laughs at certainty.', wrong:'The comedy can hide how radical the philosophy is.', why:'It keeps the Laozi project from becoming too solemn.' },
  { slug:'tsai-zen', cover:'reference-covers/tsai-zen.jpg', title:'Zen Speaks', author:'C. C. Tsai', kind:'Buddhist parallel', right:'Good for visualizing sudden insight, paradox, and teaching by interruption.', wrong:'Zen and Daoism overlap historically but are not interchangeable.', why:'It helps compare Daoist non-forcing with Buddhist awakening without flattening them.' }
];
window.SLINGERLAND_DEEP = {
  title: 'Why Slingerland Is The Best Modern Doorway',
  points: [
    'He understands wu-wei as a trained cognitive state, not as laziness or vague “flow.”',
    'He connects early Chinese thought to cognitive science without making the ancient texts seem primitive.',
    'He explains de as embodied credibility: charisma that vanishes the moment it becomes performance.',
    'He is especially useful for this project because the Dao De Jing repeatedly asks the impossible-sounding question: how do you become natural on purpose?'
  ],
  caution: 'My one caution: Slingerland is a doorway, not the whole house. After he makes the paradox clear, we still need the Chinese text, commentators, ritual history, Buddhism, politics, and ordinary life.'
};
