/* =============================================================
   ONE-SENTENCE SUMMARIES — the Daily-Stoic spine of the book
   For each chapter: the cleanest, deepest meaning a reader who
   has never opened the Daodejing can carry away in one breath.
   - cn  : a 4–8 character Chinese gloss (often a coined motto)
   - en  : one English sentence, plain and unsentimental
   - th  : one Thai sentence, modern professional, ผม-voice when needed
   ============================================================ */
window.SUMMARIES = {
  1:  { cn:"名之即縛之",       en:"The moment you name something, you have made it smaller.",                                            th:"ทันทีที่ตั้งชื่ออะไร เราก็ทำให้มันเล็กลง" },
  2:  { cn:"美醜並生",          en:"Beautiful and ugly arrive in the same breath; you cannot have one without summoning the other.",       th:"ความงามและความน่าเกลียดเกิดขึ้นพร้อมกัน เรียกข้างหนึ่ง อีกข้างตามมาเสมอ" },
  3:  { cn:"勿揚則民安",        en:"A society stops fighting over things its rulers stop showing off.",                                    th:"สังคมจะหยุดทะเลาะเรื่องอะไรก็ตามที่ผู้นำเลิกอวด" },
  4:  { cn:"虛而不竭",          en:"What is empty in form is precisely what is inexhaustible in use.",                                     th:"สิ่งที่ดูว่างเปล่าทางรูป กลับใช้ไม่หมดทางประโยชน์" },
  5:  { cn:"天地不仁",          en:"The universe is not cruel; it is impersonal, and that is the harder mercy.",                            th:"จักรวาลไม่ได้โหดร้าย เพียงแต่ไม่ได้สนใจเรา และนั่นคือความเมตตาที่ยอมรับยากที่สุด" },
  6:  { cn:"谷神不死",          en:"What yields outlives what insists.",                                                                   th:"สิ่งที่ยอมโค้ง อยู่ได้นานกว่าสิ่งที่ยืนยันว่าต้องตรง" },
  7:  { cn:"無私故能成",        en:"You become most yourself when you stop trying to be seen as yourself.",                                th:"เราจะเป็นตัวเองที่สุด เมื่อหยุดพยายามให้ใครเห็นว่าเราเป็นตัวเอง" },
  8:  { cn:"上善若水",          en:"Be water: it does not push back, so it never stores the impact that breaks rocks.",                    th:"จงเป็นน้ำ — มันไม่ดันกลับ จึงไม่สะสมแรงกระแทกที่ทำให้ตัวเองแตก" },
  9:  { cn:"持而盈之，不如其已", en:"Knowing when to stop is the only skill that scales.",                                                  th:"การรู้ว่าเมื่อไรควรพอ คือทักษะเดียวที่ใช้ได้กับทุกระดับของชีวิต" },
  10: { cn:"專氣致柔",          en:"Hold body and spirit together as one breath, and stop polishing the mirror.",                          th:"ถือกายและใจไว้เป็นลมหายใจเดียว แล้วหยุดเช็ดกระจกของตัวเอง" },
  11: { cn:"無之以為用",        en:"In every made thing, the empty space is what you actually use.",                                       th:"ในของทุกชิ้นที่สร้างขึ้น ที่ว่างนั่นแหละคือสิ่งที่เราใช้จริง" },
  12: { cn:"為腹不為目",        en:"Feed the belly, not the eye — your basic needs are modest; your manufactured wants are not.",          th:"เลี้ยงท้อง อย่าเลี้ยงตา — ความต้องการพื้นฐานของเราน้อยนิด แต่ความอยากที่ถูกสร้างไม่เคยพอ" },
  13: { cn:"寵辱若驚",          en:"Praise and disgrace are the same neural circuit, running in opposite directions.",                     th:"คำชมกับคำดูถูกใช้วงจรประสาทชุดเดียวกัน เพียงแต่สวนทางกัน" },
  14: { cn:"視之不見",          en:"What you cannot quite see, hear, or grasp is the thing actually holding everything else up.",          th:"สิ่งที่เรามองไม่ค่อยเห็น ฟังไม่ค่อยได้ จับไม่ค่อยถนัด คือสิ่งที่ค้ำทุกอย่างไว้" },
  15: { cn:"豫兮若冬涉川",      en:"The old masters move like someone crossing a frozen river — careful, unrushed, alert.",                th:"ปรมาจารย์รุ่นเก่าเคลื่อนไหวเหมือนคนข้ามแม่น้ำที่กลายเป็นน้ำแข็ง — ระมัดระวัง ไม่รีบ ตื่นรู้" },
  16: { cn:"歸根曰靜",          en:"Stillness is not the absence of activity; it is the brain returning to its root and reorganizing.",    th:"ความนิ่งไม่ใช่การไม่ทำอะไร แต่คือจิตกลับสู่รากแล้วเรียงตัวเองใหม่" },
  17: { cn:"太上下知有之",      en:"The best leader is barely noticed; the worst is loved or feared.",                                     th:"ผู้นำที่ดีที่สุด คนแทบไม่รู้ว่ามีอยู่ ผู้นำที่แย่ที่สุดคือคนที่คนรักหรือคนกลัว" },
  18: { cn:"大道廢，有仁義",    en:"Once a virtue has to be named, it is already in trouble.",                                              th:"เมื่อใดก็ตามที่คุณธรรมต้องถูกเรียกชื่อ คุณธรรมนั้นก็สูญไปครึ่งหนึ่งแล้ว" },
  19: { cn:"絕聖棄智",          en:"Less culture, not more — drop three things, and the people will be a hundredfold better.",             th:"วัฒนธรรมน้อย ๆ ดีกว่ามาก ๆ — วางสามสิ่ง ผู้คนจะดีขึ้นร้อยเท่า" },
  20: { cn:"獨異於人",          en:"To value being fed by the mother — by quiet, by what no one applauds — is not weakness. It is a different food.", th:"การเลือกรับอาหารจากแม่ — จากความเงียบ จากสิ่งที่ไม่มีใครปรบมือให้ — ไม่ใช่ความอ่อนแอ แต่เป็นอาหารอีกชนิดหนึ่ง" },
  21: { cn:"孔德之容",          en:"Substance shapes virtue, not the other way around.",                                                   th:"เนื้อแท้กำหนดคุณธรรม ไม่ใช่คุณธรรมที่กำหนดเนื้อแท้" },
  22: { cn:"曲則全",            en:"Bend, and you stay whole — the storm strengthens what gives way to it.",                              th:"โค้งให้ได้ แล้วยังครบ — พายุไม่ทำลายสิ่งที่ยอมโค้ง เพียงแต่ทำให้แข็งแรงขึ้น" },
  23: { cn:"飄風不終朝",        en:"No storm lasts a morning; nothing forced sustains itself.",                                            th:"ไม่มีพายุไหนทนหนึ่งเช้า ไม่มีสิ่งใดที่ฝืนแล้วอยู่ได้" },
  24: { cn:"企者不立",          en:"Standing on tiptoes does not make you taller; it makes you fall faster.",                              th:"การเขย่งปลายเท้าไม่ทำให้สูงขึ้น แต่ทำให้ล้มเร็วขึ้น" },
  25: { cn:"道法自然",          en:"The Way is not handed down by a higher authority — it follows what is so of itself.",                  th:"ทางไม่ได้ถูกสั่งมาจากเบื้องบน ทางตามธรรมชาติของสรรพสิ่ง" },
  26: { cn:"重為輕根",          en:"Heaviness is the root of lightness; the calm center is where movement actually lives.",                th:"ความหนักคือรากของความเบา จุดนิ่งคือที่ซึ่งการเคลื่อนไหวอาศัยอยู่" },
  27: { cn:"善行無轍跡",        en:"Good work leaves no trace — the doer's signature is missing on purpose.",                              th:"งานที่ดีไม่ทิ้งร่องรอย — ผู้ทำงานตั้งใจไม่เซ็นชื่อไว้" },
  28: { cn:"知雄守雌",          en:"Know the strong; live in the soft. Know the bright; dwell in the dim.",                                th:"รู้จักสิ่งแข็งแรง แต่อยู่กับสิ่งอ่อนโยน รู้จักความสว่าง แต่อาศัยอยู่ในความสลัว" },
  29: { cn:"天下神器，不可為也", en:"You cannot grip the world; the harder you grip, the more it spoils in your hand.",                     th:"จับโลกไว้ในมือไม่ได้ ยิ่งจับแน่น มันยิ่งพังในมือ" },
  30: { cn:"以道佐人主者，不以兵強天下", en:"Force has a way of returning to the one who used it.",                                          th:"พลังมักย้อนกลับไปหาคนที่ปล่อยมัน" },
  31: { cn:"夫兵者不祥之器",    en:"Weapons are tools of mourning — when you must use them, do so with the gravity of a funeral.",          th:"อาวุธคือเครื่องมือของการไว้อาลัย — หากจำเป็นต้องใช้ ใช้ด้วยน้ำหนักของงานศพ" },
  32: { cn:"道常無名",          en:"The Way has no name on purpose, because every name would shrink it.",                                  th:"ทางไม่มีชื่อ — เพราะชื่อใดก็ตามจะทำให้มันเล็กลง" },
  33: { cn:"自知者明",          en:"Knowing others is wisdom; knowing yourself is calibration.",                                            th:"รู้คนอื่นเป็นปัญญา รู้ตัวเองคือการสอบเทียบ" },
  34: { cn:"大道氾兮",          en:"What is truly great does not announce itself.",                                                        th:"สิ่งที่ยิ่งใหญ่จริง ไม่ประกาศตัวเอง" },
  35: { cn:"執大象，天下往",    en:"Hold the great pattern, and people come to you of their own accord.",                                  th:"ถือแบบแผนใหญ่ไว้ คนจะมาหาเราเอง" },
  36: { cn:"柔弱勝剛強",        en:"To shrink something, first let it expand; to weaken it, first let it strengthen — the law of reversal.", th:"จะหดอะไร ปล่อยให้ขยายก่อน จะอ่อนอะไร ปล่อยให้แข็งก่อน — กฎของการกลับด้าน" },
  37: { cn:"道常無為",          en:"Stop intervening, and most things govern themselves.",                                                 th:"หยุดยุ่ง สิ่งต่าง ๆ ก็จัดการตัวเองได้" },
  38: { cn:"上德不德",          en:"Real virtue does not look virtuous — the moment it does, the substance has already left.",             th:"คุณธรรมที่แท้จริงไม่ได้ดูเหมือนคุณธรรม — พอมันดูเหมือนคุณธรรม เนื้อแท้ได้หายไปแล้ว" },
  39: { cn:"得一者",            en:"Everything that lasts holds the One — the unifying thread underneath the parts.",                      th:"ทุกสิ่งที่ยั่งยืนถือ \"หนึ่ง\" ไว้ — เส้นด้ายเดียวที่ร้อยทุกชิ้นส่วน" },
  40: { cn:"反者道之動",        en:"The Way moves by reversing; weakness is its working hand.",                                            th:"ทางเคลื่อนด้วยการกลับด้าน ความอ่อนคือมือทำงานของมัน" },
  41: { cn:"上士聞道，勤而行之", en:"The best students hear the Way and walk; the average laugh, and only their laughter is honest.",      th:"ลูกศิษย์ที่ดีที่สุดได้ยินทางแล้วเดิน คนธรรมดาหัวเราะ — เสียงหัวเราะของพวกเขาคือสิ่งที่ซื่อสัตย์ที่สุด" },
  42: { cn:"萬物負陰而抱陽",    en:"Everything carries a shadow on its back and an opposite in its arms — there is no pure side.",          th:"ทุกสิ่งแบกเงาไว้ที่หลัง และโอบสิ่งตรงข้ามไว้ในอ้อมแขน — ไม่มีด้านที่บริสุทธิ์" },
  43: { cn:"天下之至柔",        en:"The softest thing in the world rides through the hardest.",                                            th:"สิ่งที่อ่อนที่สุดในโลก ขี่ผ่านสิ่งที่แข็งที่สุดได้" },
  44: { cn:"知足不辱",          en:"Know what is enough, and you cannot be disgraced; know where to stop, and you cannot be endangered.",  th:"รู้ว่าพอแค่ไหน ก็ไม่อับอาย รู้ว่าหยุดที่ไหน ก็ไม่อันตราย" },
  45: { cn:"大成若缺",          en:"What is most complete looks unfinished — the final polish is the one not applied.",                    th:"สิ่งที่สมบูรณ์ที่สุดมักดูยังไม่เสร็จ — การขัดเงาครั้งสุดท้ายคือครั้งที่ไม่ได้ลง" },
  46: { cn:"知足之足，常足矣",  en:"The contentment of being content is the only contentment that does not run out.",                       th:"ความพอใจที่เกิดจากการรู้พอ คือความพอใจอย่างเดียวที่ไม่มีวันหมด" },
  47: { cn:"不出戶，知天下",    en:"You can know the world without leaving the room — and you cannot know it any other way.",              th:"รู้จักโลกได้โดยไม่ออกจากห้อง — และนั่นคือทางรู้ที่แท้จริง" },
  48: { cn:"為學日益，為道日損", en:"Learning piles up; the Way takes things off the pile.",                                                 th:"การเรียนคือการสะสมขึ้นไป ทางคือการเอาออก" },
  49: { cn:"聖人無常心",        en:"The wise person has no fixed mind; they take the people's mind as their mind.",                         th:"คนฉลาดไม่ยึดใจตายตัว เขาเอาใจคนเป็นใจตัวเอง" },
  50: { cn:"出生入死",          en:"Birth and death are the same door, and the trick is not to keep stepping over it on purpose.",         th:"เกิดและตายคือประตูเดียวกัน เคล็ดลับคือการไม่เดินข้ามไปมาเล่น ๆ" },
  51: { cn:"道生之，德畜之",    en:"The Way births it; virtue feeds it; circumstance shapes it; you neither own nor steer.",                 th:"ทางให้กำเนิด คุณธรรมเลี้ยงดู สถานการณ์ขึ้นรูป เราไม่ได้เป็นเจ้าของและไม่ได้บังคับ" },
  52: { cn:"既得其母",          en:"Find the mother, and the children come for free.",                                                     th:"หาแม่ให้เจอ ลูก ๆ ก็ตามมาเอง" },
  53: { cn:"使我介然有知",      en:"When the granaries are empty and the courtiers wear designer clothes, the state is not great — it is robbed.", th:"เมื่อยุ้งฉางว่างเปล่า แต่ขุนนางใส่เสื้อผ้าหรูหรา รัฐนั้นไม่ใช่รัฐยิ่งใหญ่ — แต่เป็นรัฐที่ถูกปล้น" },
  54: { cn:"善建者不拔",        en:"What is well rooted does not get pulled up; what is well held does not slip away.",                    th:"สิ่งที่หยั่งรากดีไม่ถูกถอน สิ่งที่ถือดีไม่ลื่นหลุด" },
  55: { cn:"含德之厚，比於赤子", en:"The fully alive person looks like an infant — soft, unguarded, and somehow harder to harm.",          th:"คนที่มีชีวิตชีวาที่สุดดูเหมือนทารก — อ่อน ไม่ป้องกันตัว และทำร้ายได้ยากกว่าที่คิด" },
  56: { cn:"知者不言",          en:"Those who know do not need to say so; those who keep saying so usually do not know.",                  th:"คนที่รู้ไม่ต้องบอก คนที่บอกตลอดมักจะไม่รู้" },
  57: { cn:"以正治國，以奇用兵", en:"Govern with the straightforward; fight with the unexpected; win the world by leaving it alone.",       th:"ปกครองด้วยความตรงไปตรงมา รบด้วยสิ่งที่ไม่คาดคิด ชนะโลกด้วยการปล่อยวาง" },
  58: { cn:"禍兮福之所倚",      en:"Misfortune is what fortune leans on; comfort is where trouble is already growing.",                    th:"ทุกข์คือที่โชคพิงอยู่ ความสบายคือที่ซึ่งปัญหากำลังงอก" },
  59: { cn:"治人事天，莫若嗇",  en:"In governing people and serving heaven, nothing beats restraint.",                                      th:"ในการปกครองคนและรับใช้ฟ้า ไม่มีอะไรดีกว่าการรู้จักยับยั้ง" },
  60: { cn:"治大國，若烹小鮮",  en:"Govern a great state the way you cook a small fish — disturb it less than you think you should.",       th:"ปกครองรัฐใหญ่เหมือนทอดปลาตัวเล็ก — รบกวนน้อยกว่าที่คิดว่าควร" },
  61: { cn:"大邦者下流",        en:"The big nation should sit downstream and let the small ones flow toward it.",                          th:"ชาติใหญ่ควรอยู่ปลายน้ำ ปล่อยให้ชาติเล็กไหลมาหา" },
  62: { cn:"道者，萬物之奧",    en:"The Way is the secret hiding place of all things — refuge for the good, and the only thing keeping the bad alive.", th:"ทางคือที่ซ่อนของทุกสิ่ง — เป็นที่พักของคนดี และเป็นสิ่งเดียวที่ยังให้คนชั่วรอดอยู่ได้" },
  63: { cn:"圖難於其易",        en:"Tackle the hard while it is still easy; tackle the great while it is still small.",                   th:"จัดการสิ่งยากตอนที่มันยังง่าย จัดการสิ่งใหญ่ตอนที่มันยังเล็ก" },
  64: { cn:"千里之行，始於足下", en:"A thousand-mile journey begins under the foot — and most failures happen near the finish, not the start.", th:"การเดินทางพันลี้เริ่มที่ปลายเท้า — และความล้มเหลวส่วนใหญ่เกิดใกล้เส้นชัย ไม่ใช่ที่จุดเริ่ม" },
  65: { cn:"古之善為道者，非以明民", en:"The old masters did not enlighten people; they kept them simple — sophistication breeds the wrong cleverness.", th:"ปรมาจารย์รุ่นเก่าไม่ได้ทำให้คนรู้ พวกเขาทำให้คนเรียบง่าย — ความซับซ้อนช่วยผลิตความฉลาดผิดแบบ" },
  66: { cn:"江海所以能為百谷王", en:"The sea is king of a hundred valleys because it sits below them all.",                                th:"ทะเลเป็นราชาของหุบเขาร้อยลูก เพราะมันอยู่ต่ำกว่าทั้งหมด" },
  67: { cn:"我有三寶",          en:"Three treasures: mercy, frugality, and the refusal to be first — drop any one, and the other two collapse.", th:"สามขุมทรัพย์ — เมตตา ประหยัด และไม่กล้าออกหน้า — ทิ้งสิ่งใดสิ่งหนึ่ง อีกสองข้อพังตาม" },
  68: { cn:"善為士者不武",      en:"The best fighter does not show fight; the best leader does not raise their voice.",                    th:"นักรบที่ดีที่สุดไม่แสดงท่าทีรบ ผู้นำที่ดีที่สุดไม่เอ่ยเสียงดัง" },
  69: { cn:"用兵有言",          en:"In conflict, prefer the position that has nothing to lose — that is where the win actually lives.",   th:"ในความขัดแย้ง เลือกฝั่งที่ไม่มีอะไรจะเสีย — ที่นั่นคือที่ชัยชนะอยู่" },
  70: { cn:"吾言甚易知",        en:"My words are easy to understand and almost no one understands them — that is the whole problem.",     th:"คำพูดของผมเข้าใจง่าย แต่แทบไม่มีใครเข้าใจ — และนั่นคือปัญหาทั้งหมด" },
  71: { cn:"知不知，上",        en:"Knowing that you do not know is the highest form of knowing.",                                          th:"การรู้ว่าตัวเองไม่รู้ คือการรู้ระดับสูงสุด" },
  72: { cn:"民不畏威",          en:"When the people stop fearing fear, that is the moment the real fear arrives — and it is not theirs.",  th:"เมื่อประชาชนหยุดกลัวอำนาจ นั่นคือจุดที่ความกลัวที่แท้จริงมาถึง — และความกลัวนั้นไม่ใช่ของพวกเขาแล้ว" },
  73: { cn:"天網恢恢，疏而不失", en:"Heaven's net is wide and loose-meshed, and yet nothing slips through.",                              th:"ตาข่ายของฟ้ากว้างและตาห่าง แต่ไม่มีสิ่งใดเล็ดลอด" },
  74: { cn:"民不畏死",          en:"When people no longer fear death, threatening them with death stops working — and now you have a problem.", th:"เมื่อประชาชนไม่กลัวความตายแล้ว การข่มขู่ด้วยความตายก็หมดผล — แล้วเราก็มีปัญหาใหญ่" },
  75: { cn:"民之飢，以其上食稅之多", en:"Hungry people are hungry because their rulers ate too much.",                                       th:"คนหิวเพราะผู้ปกครองกินมากเกินไป" },
  76: { cn:"柔弱者生之徒",      en:"Soft and pliable belong to life; hard and rigid belong to death.",                                     th:"อ่อนและงอได้ คือฝั่งของสิ่งมีชีวิต แข็งและตรง คือฝั่งของความตาย" },
  77: { cn:"天之道，損有餘",    en:"Heaven takes from those who have too much and gives to those who have too little — humans run this function in reverse.", th:"ฟ้าเอาจากคนที่มีมากเกินมาให้คนที่มีน้อยเกิน มนุษย์ทำตรงข้าม" },
  78: { cn:"正言若反",          en:"True words sound backwards — because reality is a Möbius strip and language is a piece of paper.",     th:"ถ้อยคำที่จริงฟังเหมือนกลับด้าน — เพราะความจริงคือแถบเมอบีอุส แต่ภาษาคือกระดาษแผ่นเดียว" },
  79: { cn:"報怨以德",          en:"Settled grievances always leave a residue; the wise person holds the unfavorable half of the contract.", th:"ความขัดเคืองที่ยุติแล้วย่อมเหลือกากตะกอนไว้เสมอ คนฉลาดยอมถือด้านเสียเปรียบ" },
  80: { cn:"小國寡民",          en:"A small country with few people — tools enough but used little, food sweet, clothes beautiful, customs joyful.", th:"รัฐเล็ก ประชากรน้อย — เครื่องมือมีพอ แต่ใช้น้อย อาหารหวาน เสื้อผ้าสวย ขนบธรรมเนียมร่าเริง" },
  81: { cn:"信言不美",          en:"True words are not pretty; pretty words are not true. The book closes by demonstrating its own flaw, on purpose.", th:"ถ้อยคำที่จริงไม่สวย ถ้อยคำที่สวยไม่จริง หนังสือปิดท้ายด้วยการยอมรับจุดอ่อนของตัวเอง อย่างจงใจ" }
};
